import type { AssessmentPrompt, Grade, Subject } from "./types";

function tok(text: string, tags: string[] = []): { text: string; tags: string[] } {
  return { text, tags };
}

export const ASSESSMENT_PROMPTS: AssessmentPrompt[] = [
  {
    id: "read-g1-boat",
    subject: "reading",
    grade: 1,
    title: "The Little Blue Boat",
    instruction: "Ask the child to read the lines slowly. Mark words that were wrong, skipped, or needed a long pause.",
    displayText: "The dog can run. The cat can nap. Dad and I sit by the mat.",
    tokens: [
      tok("The", ["sight", "position:begin"]),
      tok("dog", ["letter:d", "position:begin"]),
      tok("can", ["sight"]),
      tok("run", ["position:end"]),
      tok("The", ["sight"]),
      tok("cat", ["position:begin"]),
      tok("can", ["sight"]),
      tok("nap", ["position:end"]),
      tok("Dad", ["letter:d", "position:begin"]),
      tok("and", ["sight"]),
      tok("I", ["sight"]),
      tok("sit", ["position:end"]),
      tok("by", ["sight"]),
      tok("the", ["sight"]),
      tok("mat", ["position:end"]),
    ],
  },
  {
    id: "read-g2-crow",
    subject: "reading",
    grade: 2,
    title: "Clever Crow",
    instruction: "Listen for blends (bl, cl, st) and longer words. Tap any word that was guessed, skipped, or paused.",
    displayText:
      "A clever crow found a jug with a little water. It dropped small stones in, and the water rose to the top.",
    tokens: [
      tok("A", ["sight", "position:begin"]),
      tok("clever", ["blend:cl", "multisyllable", "position:begin"]),
      tok("crow", ["blend:cr", "position:begin"]),
      tok("found", ["position:end"]),
      tok("a", ["sight"]),
      tok("jug"),
      tok("with", ["sight"]),
      tok("a", ["sight"]),
      tok("little", ["multisyllable"]),
      tok("water", ["multisyllable", "position:end"]),
      tok("It", ["sight"]),
      tok("dropped", ["blend:dr", "position:end"]),
      tok("small", ["blend:sm"]),
      tok("stones", ["blend:st", "position:begin"]),
      tok("in"),
      tok("and", ["sight"]),
      tok("the", ["sight"]),
      tok("water", ["multisyllable"]),
      tok("rose"),
      tok("to", ["sight"]),
      tok("the", ["sight"]),
      tok("top", ["position:end"]),
    ],
  },
  {
    id: "read-g3-garden",
    subject: "reading",
    grade: 3,
    title: "The Community Garden",
    instruction: "Listen for longer words and whether the child keeps going through the middle and end of each word.",
    displayText:
      "Every Saturday, the neighbourhood children gather at the community garden to water vegetables and celebrate the harvest together.",
    tokens: [
      tok("Every", ["multisyllable", "position:begin"]),
      tok("Saturday", ["multisyllable"]),
      tok("the", ["sight"]),
      tok("neighbourhood", ["multisyllable"]),
      tok("children", ["multisyllable", "blend:ch"]),
      tok("gather", ["position:end"]),
      tok("at", ["sight"]),
      tok("the", ["sight"]),
      tok("community", ["multisyllable"]),
      tok("garden", ["multisyllable", "position:end"]),
      tok("to", ["sight"]),
      tok("water", ["multisyllable"]),
      tok("vegetables", ["multisyllable"]),
      tok("and", ["sight"]),
      tok("celebrate", ["multisyllable", "blend:cl", "position:begin"]),
      tok("the", ["sight"]),
      tok("harvest", ["multisyllable", "position:end"]),
      tok("together", ["multisyllable"]),
    ],
  },
  {
    id: "num-g1-count-20",
    subject: "numeracy",
    grade: 1,
    title: "Count 1 to 20",
    instruction: "Ask the child to count from 1 to 20. Tap any number that was skipped, swapped, or needed a long pause.",
    displayText: "1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20",
    tokens: [
      tok("1"),
      tok("2"),
      tok("3"),
      tok("4"),
      tok("5"),
      tok("6"),
      tok("7"),
      tok("8"),
      tok("9"),
      tok("10", ["decade", "decade:10"]),
      tok("11"),
      tok("12"),
      tok("13"),
      tok("14"),
      tok("15"),
      tok("16"),
      tok("17"),
      tok("18"),
      tok("19"),
      tok("20", ["decade"]),
    ],
  },
  {
    id: "num-g2-decades",
    subject: "numeracy",
    grade: 2,
    title: "Across the tens",
    instruction: "Ask the child to say the sequence. Watch especially around 29–30 and other ten-jumps.",
    displayText: "10, 20, 28, 29, 30, 31, 40, 58, 59, 60",
    tokens: [
      tok("10", ["decade"]),
      tok("20", ["decade"]),
      tok("28"),
      tok("29"),
      tok("30", ["decade", "decade:30"]),
      tok("31"),
      tok("40", ["decade"]),
      tok("58"),
      tok("59"),
      tok("60", ["decade"]),
    ],
  },
  {
    id: "num-g3-place",
    subject: "numeracy",
    grade: 3,
    title: "Three-digit numbers",
    instruction: "Ask the child to read each number aloud. Mark any number named with the wrong place value.",
    displayText: "108, 199, 200, 245, 350, 499, 500",
    tokens: [
      tok("108", ["place-value"]),
      tok("199", ["place-value"]),
      tok("200", ["place-value", "decade"]),
      tok("245", ["place-value"]),
      tok("350", ["place-value"]),
      tok("499", ["place-value"]),
      tok("500", ["place-value", "decade"]),
    ],
  },
  {
    id: "num-g2-backward",
    subject: "numeracy",
    grade: 2,
    title: "Count backward from 20",
    instruction: "Ask the child to count backward from 20 to 10. Mark slips or long pauses.",
    displayText: "20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10",
    tokens: [
      tok("20", ["backward", "decade"]),
      tok("19", ["backward"]),
      tok("18", ["backward"]),
      tok("17", ["backward"]),
      tok("16", ["backward"]),
      tok("15", ["backward"]),
      tok("14", ["backward"]),
      tok("13", ["backward"]),
      tok("12", ["backward"]),
      tok("11", ["backward"]),
      tok("10", ["backward", "decade", "decade:10"]),
    ],
  },
];

export function getPrompt(id: string): AssessmentPrompt | undefined {
  return ASSESSMENT_PROMPTS.find((p) => p.id === id);
}

export function promptsFor(subject: Subject, grade: Grade): AssessmentPrompt[] {
  return ASSESSMENT_PROMPTS.filter((p) => p.subject === subject && p.grade === grade);
}

export function defaultPrompt(subject: Subject, grade: Grade): AssessmentPrompt {
  return promptsFor(subject, grade)[0];
}
