import type { AssessmentPrompt, Grade, Subject } from "./types";

function tok(text: string, tags: string[] = []): { text: string; tags: string[] } {
  return { text, tags };
}

export const ASSESSMENT_PROMPTS: AssessmentPrompt[] = [
  {
    id: "read-g1-boat",
    subject: "reading",
    grade: 1,
    title: "The Little Blue Boat",
    instruction: "Ask the child to read the lines slowly. Mark words that were wrong, skipped, or needed a long pause.",
    displayText: "The dog can run. The cat can nap. Dad and I sit by the mat.",
    tokens: [
      tok("The", ["sight", "position:begin"]),
      tok("dog", ["letter:d", "position:begin"]),
      tok("can", ["sight"]),
      tok("run", ["position:end"]),
      tok("The", ["sight"]),
      tok("cat", ["position:begin"]),
      tok("can", ["sight"]),
      tok("nap", ["position:end"]),
      tok("Dad", ["letter:d", "position:begin"]),
      tok("and", ["sight"]),
      tok("I", ["sight"]),
      tok("sit", ["position:end"]),
      tok("by", ["sight"]),
      tok("the", ["sight"]),
      tok("mat", ["position:end"]),
    ],
    titleHi: "मेरी बिल्ली और कुत्ता",
    instructionHi:
      "बच्चे से पंक्तियाँ धीरे-धीरे पढ़ने को कहें। जो शब्द गलत, छूटे या देर से बोले उन्हें चिह्नित करें।",
    displayTextHi: "बिल्ली सोई। कुत्ता दौड़ा। दादा और मैं बैठे हैं।",
    tokensHi: [
      tok("बिल्ली", ["letter:b", "multisyllable", "position:begin"]),
      tok("सोई", ["position:end"]),
      tok("कुत्ता", ["multisyllable", "position:begin"]),
      tok("दौड़ा", ["letter:d", "position:begin"]),
      tok("दादा", ["letter:d", "position:begin"]),
      tok("और", ["sight"]),
      tok("मैं", ["sight", "position:begin"]),
      tok("बैठे", ["position:begin"]),
      tok("हैं", ["sight", "position:end"]),
    ],
  },
  {
    id: "read-g2-crow",
    subject: "reading",
    grade: 2,
    title: "Clever Crow",
    instruction: "Listen for blends (bl, cl, st) and longer words. Tap any word that was guessed, skipped, or paused.",
    displayText:
      "A clever crow found a jug with a little water. It dropped small stones in, and the water rose to the top.",
    titleHi: "चतुर कौआ",
    instructionHi:
      "संयुक्त व्यंजन (जैसे त्थ, ड्ड) और लंबे शब्दों पर ध्यान दें। जो शब्द अंदाज़ से, छूटे या रुककर बोला जाए उसे टैप करें।",
    displayTextHi:
      "एक चतुर कौआ प्यासा था। उसे पानी का घड़ा मिला। उसने छोटे-छोटे पत्थर डाले और पानी ऊपर आ गया।",
    tokensHi: [
      tok("एक", ["sight", "position:begin"]),
      tok("चतुर", ["multisyllable", "position:begin"]),
      tok("कौआ", ["multisyllable"]),
      tok("प्यासा", ["multisyllable", "position:end"]),
      tok("था", ["sight"]),
      tok("उसे", ["sight"]),
      tok("पानी", ["multisyllable", "position:begin"]),
      tok("का", ["sight"]),
      tok("घड़ा", ["multisyllable"]),
      tok("मिला", ["position:end"]),
      tok("उसने", ["sight", "position:begin"]),
      tok("छोटे", ["position:begin"]),
      tok("पत्थर", ["multisyllable", "position:end"]),
      tok("डाले", ["position:end"]),
      tok("और", ["sight"]),
      tok("पानी", ["multisyllable"]),
      tok("ऊपर", ["position:begin"]),
      tok("आ", ["position:begin"]),
      tok("गया", ["sight", "position:end"]),
    ],
    tokens: [
      tok("A", ["sight", "position:begin"]),
      tok("clever", ["blend:cl", "multisyllable", "position:begin"]),
      tok("crow", ["blend:cr", "position:begin"]),
      tok("found", ["position:end"]),
      tok("a", ["sight"]),
      tok("jug"),
      tok("with", ["sight"]),
      tok("a", ["sight"]),
      tok("little", ["multisyllable"]),
      tok("water", ["multisyllable", "position:end"]),
      tok("It", ["sight"]),
      tok("dropped", ["blend:dr", "position:end"]),
      tok("small", ["blend:sm"]),
      tok("stones", ["blend:st", "position:begin"]),
      tok("in"),
      tok("and", ["sight"]),
      tok("the", ["sight"]),
      tok("water", ["multisyllable"]),
      tok("rose"),
      tok("to", ["sight"]),
      tok("the", ["sight"]),
      tok("top", ["position:end"]),
    ],
  },
  {
    id: "read-g3-garden",
    subject: "reading",
    grade: 3,
    title: "The Community Garden",
    instruction: "Listen for longer words and whether the child keeps going through the middle and end of each word.",
    displayText:
      "Every Saturday, the neighbourhood children gather at the community garden to water vegetables and celebrate the harvest together.",
    titleHi: "सामुदायिक बगीचा",
    instructionHi:
      "लंबे शब्दों पर ध्यान दें और देखें कि बच्चा हर शब्द के बीच और अंत तक पढ़ पा रहा है या नहीं।",
    displayTextHi:
      "हर शनिवार पड़ोस के बच्चे सामुदायिक बगीचे में आते हैं। वे सब्ज़ियों को पानी देते हैं और साथ मिलकर फ़सल का जश्न मनाते हैं।",
    tokensHi: [
      tok("हर", ["sight", "position:begin"]),
      tok("शनिवार", ["multisyllable"]),
      tok("पड़ोस", ["multisyllable", "position:begin"]),
      tok("के", ["sight"]),
      tok("बच्चे", ["multisyllable", "position:begin"]),
      tok("सामुदायिक", ["multisyllable"]),
      tok("बगीचे", ["multisyllable", "position:end"]),
      tok("में", ["sight"]),
      tok("आते", ["position:end"]),
      tok("हैं", ["sight"]),
      tok("वे", ["sight"]),
      tok("सब्ज़ियों", ["multisyllable", "position:begin"]),
      tok("को", ["sight"]),
      tok("पानी", ["multisyllable"]),
      tok("देते", ["position:end"]),
      tok("हैं", ["sight"]),
      tok("और", ["sight"]),
      tok("साथ", ["position:end"]),
      tok("मिलकर", ["multisyllable"]),
      tok("फ़सल", ["multisyllable", "position:begin"]),
      tok("का", ["sight"]),
      tok("जश्न", ["multisyllable", "position:end"]),
      tok("मनाते", ["multisyllable", "position:end"]),
      tok("हैं", ["sight"]),
    ],
    tokens: [
      tok("Every", ["multisyllable", "position:begin"]),
      tok("Saturday", ["multisyllable"]),
      tok("the", ["sight"]),
      tok("neighbourhood", ["multisyllable"]),
      tok("children", ["multisyllable", "blend:ch"]),
      tok("gather", ["position:end"]),
      tok("at", ["sight"]),
      tok("the", ["sight"]),
      tok("community", ["multisyllable"]),
      tok("garden", ["multisyllable", "position:end"]),
      tok("to", ["sight"]),
      tok("water", ["multisyllable"]),
      tok("vegetables", ["multisyllable"]),
      tok("and", ["sight"]),
      tok("celebrate", ["multisyllable", "blend:cl", "position:begin"]),
      tok("the", ["sight"]),
      tok("harvest", ["multisyllable", "position:end"]),
      tok("together", ["multisyllable"]),
    ],
  },
  {
    id: "num-g1-count-20",
    subject: "numeracy",
    grade: 1,
    title: "Count 1 to 20",
    instruction: "Ask the child to count from 1 to 20. Tap any number that was skipped, swapped, or needed a long pause.",
    displayText: "1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20",
    tokens: [
      tok("1"),
      tok("2"),
      tok("3"),
      tok("4"),
      tok("5"),
      tok("6"),
      tok("7"),
      tok("8"),
      tok("9"),
      tok("10", ["decade", "decade:10"]),
      tok("11"),
      tok("12"),
      tok("13"),
      tok("14"),
      tok("15"),
      tok("16"),
      tok("17"),
      tok("18"),
      tok("19"),
      tok("20", ["decade"]),
    ],
    titleHi: "1 से 20 तक गिनती",
    instructionHi:
      "बच्चे से 1 से 20 तक गिनने को कहें। जो संख्या छूटे, बदले या देर से बोली जाए उसे टैप करें।",
    displayTextHi:
      "एक दो तीन चार पाँच छह सात आठ नौ दस ग्यारह बारह तेरह चौदह पंद्रह सोलह सत्रह अठारह उन्नीस बीस",
    tokensHi: [
      tok("एक"),
      tok("दो"),
      tok("तीन"),
      tok("चार"),
      tok("पाँच"),
      tok("छह"),
      tok("सात"),
      tok("आठ"),
      tok("नौ"),
      tok("दस", ["decade", "decade:10"]),
      tok("ग्यारह"),
      tok("बारह"),
      tok("तेरह"),
      tok("चौदह"),
      tok("पंद्रह"),
      tok("सोलह"),
      tok("सत्रह"),
      tok("अठारह"),
      tok("उन्नीस"),
      tok("बीस", ["decade"]),
    ],
  },
  {
    id: "num-g2-decades",
    subject: "numeracy",
    grade: 2,
    title: "Across the tens",
    instruction: "Ask the child to say the sequence. Watch especially around 29–30 and other ten-jumps.",
    displayText: "10, 20, 28, 29, 30, 31, 40, 58, 59, 60",
    tokens: [
      tok("10", ["decade"]),
      tok("20", ["decade"]),
      tok("28"),
      tok("29"),
      tok("30", ["decade", "decade:30"]),
      tok("31"),
      tok("40", ["decade"]),
      tok("58"),
      tok("59"),
      tok("60", ["decade"]),
    ],
    titleHi: "दहाई पार करना",
    instructionHi:
      "बच्चे से क्रम बोलने को कहें। 29–30 और अन्य दहाई-कूदों पर ख़ास ध्यान दें।",
    displayTextHi: "दस, बीस, अट्ठाईस, उनतीस, तीस, इकतीस, चालीस, अट्ठावन, उनसठ, साठ",
    tokensHi: [
      tok("दस", ["decade"]),
      tok("बीस", ["decade"]),
      tok("अट्ठाईस"),
      tok("उनतीस"),
      tok("तीस", ["decade", "decade:30"]),
      tok("इकतीस"),
      tok("चालीस", ["decade"]),
      tok("अट्ठावन"),
      tok("उनसठ"),
      tok("साठ", ["decade"]),
    ],
  },
  {
    id: "num-g3-place",
    subject: "numeracy",
    grade: 3,
    title: "Three-digit numbers",
    instruction: "Ask the child to read each number aloud. Mark any number named with the wrong place value.",
    displayText: "108, 199, 200, 245, 350, 499, 500",
    tokens: [
      tok("108", ["place-value"]),
      tok("199", ["place-value"]),
      tok("200", ["place-value", "decade"]),
      tok("245", ["place-value"]),
      tok("350", ["place-value"]),
      tok("499", ["place-value"]),
      tok("500", ["place-value", "decade"]),
    ],
    titleHi: "तीन अंकों वाली संख्याएँ",
    instructionHi:
      "बच्चे से प्रत्येक संख्या ज़ोर से पढ़ने को कहें। जो संख्या गलत स्थानीय मान से बोली जाए उसे चिह्नित करें।",
    displayTextHi:
      "एक सौ आठ, एक सौ निन्यानवे, दो सौ, दो सौ पैंतालीस, तीन सौ पचास, चार सौ निन्यानवे, पाँच सौ",
    tokensHi: [
      tok("एक सौ आठ", ["place-value"]),
      tok("एक सौ निन्यानवे", ["place-value"]),
      tok("दो सौ", ["place-value", "decade"]),
      tok("दो सौ पैंतालीस", ["place-value"]),
      tok("तीन सौ पचास", ["place-value"]),
      tok("चार सौ निन्यानवे", ["place-value"]),
      tok("पाँच सौ", ["place-value", "decade"]),
    ],
  },
  {
    id: "num-g2-backward",
    subject: "numeracy",
    grade: 2,
    title: "Count backward from 20",
    instruction: "Ask the child to count backward from 20 to 10. Mark slips or long pauses.",
    displayText: "20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10",
    tokens: [
      tok("20", ["backward", "decade"]),
      tok("19", ["backward"]),
      tok("18", ["backward"]),
      tok("17", ["backward"]),
      tok("16", ["backward"]),
      tok("15", ["backward"]),
      tok("14", ["backward"]),
      tok("13", ["backward"]),
      tok("12", ["backward"]),
      tok("11", ["backward"]),
      tok("10", ["backward", "decade", "decade:10"]),
    ],
    titleHi: "20 से उल्टी गिनती",
    instructionHi:
      "बच्चे से 20 से 10 तक उल्टी गिनती करने को कहें। फिसलन या लंबी रुकावट को चिह्नित करें।",
    displayTextHi: "बीस, उन्नीस, अठारह, सत्रह, सोलह, पंद्रह, चौदह, तेरह, बारह, ग्यारह, दस",
    tokensHi: [
      tok("बीस", ["backward", "decade"]),
      tok("उन्नीस", ["backward"]),
      tok("अठारह", ["backward"]),
      tok("सत्रह", ["backward"]),
      tok("सोलह", ["backward"]),
      tok("पंद्रह", ["backward"]),
      tok("चौदह", ["backward"]),
      tok("तेरह", ["backward"]),
      tok("बारह", ["backward"]),
      tok("ग्यारह", ["backward"]),
      tok("दस", ["backward", "decade", "decade:10"]),
    ],
  },
];

export function getPrompt(id: string): AssessmentPrompt | undefined {
  return ASSESSMENT_PROMPTS.find((p) => p.id === id);
}

export function promptsFor(subject: Subject, grade: Grade): AssessmentPrompt[] {
  return ASSESSMENT_PROMPTS.filter((p) => p.subject === subject && p.grade === grade);
}

export function defaultPrompt(subject: Subject, grade: Grade): AssessmentPrompt {
  return promptsFor(subject, grade)[0];
}
