import type { AssessmentPrompt, Grade, Subject } from "./types";

function tok(text: string, tags: string[] = []): { text: string; tags: string[] } {
  return { text, tags };
}

export const ASSESSMENT_PROMPTS: AssessmentPrompt[] = [
  /* ══════════════════════ READING ══════════════════════ */

  /* ── Letter Recognition ─────────────────────────────── */
  {
    id: "read-letter-names",
    subject: "reading",
    grades: [1, 2],
    category: "letter-recognition",
    title: "Letter names A–P",
    instruction:
      "Point to each letter and ask its name. Tap letters that were wrong, skipped, or needed a long pause.",
    displayText: "A B C D E F G H I J K L M N O P",
    tokens: [
      tok("A", ["letter-name"]),
      tok("B", ["letter-name"]),
      tok("C", ["letter-name"]),
      tok("D", ["letter-name"]),
      tok("E", ["letter-name"]),
      tok("F", ["letter-name"]),
      tok("G", ["letter-name"]),
      tok("H", ["letter-name"]),
      tok("I", ["letter-name"]),
      tok("J", ["letter-name"]),
      tok("K", ["letter-name"]),
      tok("L", ["letter-name"]),
      tok("M", ["letter-name"]),
      tok("N", ["letter-name"]),
      tok("O", ["letter-name"]),
      tok("P", ["letter-name"]),
    ],
    titleHi: "अक्षरों के नाम A–P",
    instructionHi:
      "हर अक्षर पर उँगली रखकर नाम पूछें। जो अक्षर गलत, छूटा या देर से बोला जाए उसे टैप करें।",
  },

  /* ── Letter-Sound Recognition ───────────────────────── */
  {
    id: "read-letter-sounds",
    subject: "reading",
    grades: [1, 2],
    category: "letter-sound",
    title: "Letter sounds",
    instruction:
      "Ask for the sound each letter makes — not its name. Tap wrong, skipped, or slow sounds.",
    displayText: "b d f h m n s t p k g l r w j v z",
    tokens: [
      tok("b", ["letter-sound", "letter:b"]),
      tok("d", ["letter-sound", "letter:d"]),
      tok("f", ["letter-sound"]),
      tok("h", ["letter-sound"]),
      tok("m", ["letter-sound"]),
      tok("n", ["letter-sound"]),
      tok("s", ["letter-sound"]),
      tok("t", ["letter-sound"]),
      tok("p", ["letter-sound"]),
      tok("k", ["letter-sound"]),
      tok("g", ["letter-sound"]),
      tok("l", ["letter-sound"]),
      tok("r", ["letter-sound"]),
      tok("w", ["letter-sound"]),
      tok("j", ["letter-sound"]),
      tok("v", ["letter-sound"]),
      tok("z", ["letter-sound"]),
    ],
    titleHi: "अक्षरों की ध्वनि",
    instructionHi:
      "हर अक्षर की ध्वनि पूछें — नाम नहीं। जो ध्वनि गलत, छूटी या देर से बोली जाए उसे टैप करें।",
  },

  /* ── Simple / CVC Word Reading ──────────────────────── */
  {
    id: "read-cvc-words",
    subject: "reading",
    grades: [1, 2],
    category: "cvc-words",
    title: "Three-letter words",
    instruction:
      "Ask the child to read each word aloud. Tap words that were wrong, skipped, or needed a long pause.",
    displayText: "cat dog mat sun hop pig bat lid run bed",
    tokens: [
      tok("cat", ["cvc", "position:begin"]),
      tok("dog", ["cvc", "letter:d", "position:begin"]),
      tok("mat", ["cvc", "position:end"]),
      tok("sun", ["cvc"]),
      tok("hop", ["cvc", "position:end"]),
      tok("pig", ["cvc"]),
      tok("bat", ["cvc", "letter:b", "position:begin"]),
      tok("lid", ["cvc", "letter:d", "position:end"]),
      tok("run", ["cvc", "position:end"]),
      tok("bed", ["cvc", "letter:b", "letter:d", "position:end"]),
    ],
    titleHi: "तीन अक्षरों वाले शब्द",
    instructionHi:
      "बच्चे से हर छोटा शब्द ज़ोर से पढ़ने को कहें। जो शब्द गलत, छूटा या देर से बोला जाए उसे टैप करें।",
  },

  /* ── Consonant Blends ───────────────────────────────── */
  {
    id: "read-blend-words",
    subject: "reading",
    grades: [1, 2, 3],
    category: "consonant-blends",
    title: "Blend words: bl · cl · st",
    instruction:
      "Listen for both starting sounds. Tap words where the second consonant was dropped, swapped, or paused.",
    displayText: "blue clap stop star block flag glass stone plant",
    tokens: [
      tok("blue", ["blend:bl", "position:begin"]),
      tok("clap", ["blend:cl", "position:begin"]),
      tok("stop", ["blend:st"]),
      tok("star", ["blend:st", "position:begin"]),
      tok("block", ["blend:bl"]),
      tok("flag", ["blend:fl", "position:begin"]),
      tok("glass", ["blend:gl"]),
      tok("stone", ["blend:st", "position:begin"]),
      tok("plant", ["blend:pl"]),
    ],
    titleHi: "संयुक्त व्यंजन शब्द: क्ल · प्ल · स्ट",
    instructionHi:
      "दोनों शुरुआती ध्वनियों पर ध्यान दें। जहाँ दूसरा व्यंजन छूटे, बदले या रुकावट हो वहाँ टैप करें।",
    displayTextHi: "क्लास प्लेट स्टेशन स्टार ब्लॉक फ्लैग ग्लास स्टोन प्लांट",
    tokensHi: [
      tok("क्लास", ["blend:cl", "position:begin"]),
      tok("प्लेट", ["blend:pl", "position:begin"]),
      tok("स्टेशन", ["blend:st", "position:begin"]),
      tok("स्टार", ["blend:st", "position:begin"]),
      tok("ब्लॉक", ["blend:bl", "position:begin"]),
      tok("फ्लैग", ["blend:fl", "position:begin"]),
      tok("ग्लास", ["blend:gl", "position:begin"]),
      tok("स्टोन", ["blend:st", "position:begin"]),
      tok("प्लांट", ["blend:pl", "position:begin"]),
    ],
  },

  /* ── Word Reading ───────────────────────────────────── */
  {
    id: "read-words-1",
    subject: "reading",
    grades: [1, 2, 3],
    category: "word-reading",
    title: "Everyday words",
    instruction:
      "Ask the child to read each word. Tap words that were sounded out slowly, guessed, or skipped.",
    displayText: "the and can I to a said look make play come water little",
    tokens: [
      tok("the", ["word", "sight"]),
      tok("and", ["word", "sight"]),
      tok("can", ["word", "sight"]),
      tok("I", ["word", "sight"]),
      tok("to", ["word", "sight"]),
      tok("a", ["word", "sight"]),
      tok("said", ["word", "sight"]),
      tok("look", ["word", "sight"]),
      tok("make", ["word", "sight"]),
      tok("play", ["word", "sight"]),
      tok("come", ["word", "sight"]),
      tok("water", ["word", "multisyllable", "position:end"]),
      tok("little", ["word", "multisyllable"]),
    ],
    titleHi: "रोज़ के शब्द",
    instructionHi:
      "बच्चे से हर शब्द पढ़ने को कहें। जो शब्द धीरे-धीरे, अंदाज़ से या छूटकर पढ़ा जाए उसे टैप करें।",
    displayTextHi: "मैं और माँ वह स्कूल पानी दूध किताब खेलना घर",
    tokensHi: [
      tok("मैं", ["word", "sight"]),
      tok("और", ["word", "sight"]),
      tok("माँ", ["word", "sight"]),
      tok("वह", ["word", "sight"]),
      tok("स्कूल", ["word", "multisyllable"]),
      tok("पानी", ["word", "multisyllable", "position:end"]),
      tok("दूध", ["word", "position:end"]),
      tok("किताब", ["word", "multisyllable", "position:end"]),
      tok("खेलना", ["word", "multisyllable"]),
      tok("घर", ["word", "sight"]),
    ],
  },

  /* ── Sentence Reading ───────────────────────────────── */
  {
    id: "read-sentences-1",
    subject: "reading",
    grades: [1, 2, 3],
    category: "sentence-reading",
    title: "Short sentences",
    instruction:
      "Ask the child to read each sentence aloud. Tap words that were wrong, skipped, or paused on.",
    displayText: "The cat sat on the mat. I can hop. Look at the big dog.",
    tokens: [
      tok("The", ["sentence", "sight"]),
      tok("cat", ["sentence", "cvc", "position:begin"]),
      tok("sat", ["sentence", "cvc", "position:end"]),
      tok("on", ["sentence", "sight"]),
      tok("the", ["sentence", "sight"]),
      tok("mat", ["sentence", "cvc", "position:end"]),
      tok("I", ["sentence", "sight"]),
      tok("can", ["sentence", "sight"]),
      tok("hop", ["sentence", "cvc", "position:end"]),
      tok("Look", ["sentence", "word", "position:begin"]),
      tok("at", ["sentence", "sight"]),
      tok("the", ["sentence", "sight"]),
      tok("big", ["sentence", "cvc"]),
      tok("dog", ["sentence", "cvc", "letter:d", "position:end"]),
    ],
    titleHi: "छोटे वाक्य",
    instructionHi:
      "बच्चे से हर वाक्य ज़ोर से पढ़ने को कहें। जो शब्द गलत, छूटा या रुककर बोला जाए उसे टैप करें।",
    displayTextHi: "बिल्ली चटाई पर बैठी है। मैं कूद सकता हूँ। बड़े कुत्ते को देखो।",
    tokensHi: [
      tok("बिल्ली", ["sentence", "multisyllable", "position:begin"]),
      tok("चटाई", ["sentence", "multisyllable", "position:end"]),
      tok("पर", ["sentence", "sight"]),
      tok("बैठी", ["sentence", "position:begin"]),
      tok("है", ["sentence", "sight"]),
      tok("मैं", ["sentence", "sight"]),
      tok("कूद", ["sentence", "position:end"]),
      tok("सकता", ["sentence", "multisyllable"]),
      tok("हूँ", ["sentence", "sight"]),
      tok("बड़े", ["sentence", "position:begin"]),
      tok("कुत्ते", ["sentence", "multisyllable", "position:begin"]),
      tok("को", ["sentence", "sight"]),
      tok("देखो", ["sentence", "letter:d", "position:begin"]),
    ],
  },

  /* ── Short Passage Reading ──────────────────────────── */
  {
    id: "read-g1-boat",
    subject: "reading",
    grades: [1],
    category: "passage-reading",
    title: "The Little Blue Boat",
    instruction: "Ask the child to read the lines slowly. Mark words that were wrong, skipped, or needed a long pause.",
    displayText: "The dog can run. The cat can nap. Dad and I sit by the mat.",
    tokens: [
      tok("The", ["sentence", "sight", "position:begin"]),
      tok("dog", ["sentence", "letter:d", "position:begin"]),
      tok("can", ["sentence", "sight"]),
      tok("run", ["sentence", "position:end"]),
      tok("The", ["sentence", "sight"]),
      tok("cat", ["sentence", "position:begin"]),
      tok("can", ["sentence", "sight"]),
      tok("nap", ["sentence", "position:end"]),
      tok("Dad", ["sentence", "letter:d", "position:begin"]),
      tok("and", ["sentence", "sight"]),
      tok("I", ["sentence", "sight"]),
      tok("sit", ["sentence", "position:end"]),
      tok("by", ["sentence", "sight"]),
      tok("the", ["sentence", "sight"]),
      tok("mat", ["sentence", "position:end"]),
    ],
    titleHi: "मेरी बिल्ली और कुत्ता",
    instructionHi:
      "बच्चे से पंक्तियाँ धीरे-धीरे पढ़ने को कहें। जो शब्द गलत, छूटे या देर से बोले उन्हें चिह्नित करें।",
    displayTextHi: "बिल्ली सोई। कुत्ता दौड़ा। दादा और मैं बैठे हैं।",
    tokensHi: [
      tok("बिल्ली", ["sentence", "letter:b", "multisyllable", "position:begin"]),
      tok("सोई", ["sentence", "position:end"]),
      tok("कुत्ता", ["sentence", "multisyllable", "position:begin"]),
      tok("दौड़ा", ["sentence", "letter:d", "position:begin"]),
      tok("दादा", ["sentence", "letter:d", "position:begin"]),
      tok("और", ["sentence", "sight"]),
      tok("मैं", ["sentence", "sight", "position:begin"]),
      tok("बैठे", ["sentence", "position:begin"]),
      tok("हैं", ["sentence", "sight", "position:end"]),
    ],
  },
  {
    id: "read-g2-crow",
    subject: "reading",
    grades: [2],
    category: "passage-reading",
    title: "Clever Crow",
    instruction: "Listen for blends (bl, cl, st) and longer words. Tap any word that was guessed, skipped, or paused.",
    displayText:
      "A clever crow found a jug with a little water. It dropped small stones in, and the water rose to the top.",
    titleHi: "चतुर कौआ",
    instructionHi:
      "संयुक्त व्यंजन (जैसे त्थ, ड्ड) और लंबे शब्दों पर ध्यान दें। जो शब्द अंदाज़ से, छूटे या रुककर बोला जाए उसे टैप करें।",
    displayTextHi:
      "एक चतुर कौआ प्यासा था। उसे पानी का घड़ा मिला। उसने छोटे-छोटे पत्थर डाले और पानी ऊपर आ गया।",
    tokensHi: [
      tok("एक", ["sentence", "sight", "position:begin"]),
      tok("चतुर", ["sentence", "multisyllable", "position:begin"]),
      tok("कौआ", ["sentence", "multisyllable"]),
      tok("प्यासा", ["sentence", "multisyllable", "position:end"]),
      tok("था", ["sentence", "sight"]),
      tok("उसे", ["sentence", "sight"]),
      tok("पानी", ["sentence", "multisyllable", "position:begin"]),
      tok("का", ["sentence", "sight"]),
      tok("घड़ा", ["sentence", "multisyllable"]),
      tok("मिला", ["sentence", "position:end"]),
      tok("उसने", ["sentence", "sight", "position:begin"]),
      tok("छोटे", ["sentence", "position:begin"]),
      tok("पत्थर", ["sentence", "multisyllable", "position:end"]),
      tok("डाले", ["sentence", "position:end"]),
      tok("और", ["sentence", "sight"]),
      tok("पानी", ["sentence", "multisyllable"]),
      tok("ऊपर", ["sentence", "position:begin"]),
      tok("आ", ["sentence", "position:begin"]),
      tok("गया", ["sentence", "sight", "position:end"]),
    ],
    tokens: [
      tok("A", ["sentence", "sight", "position:begin"]),
      tok("clever", ["sentence", "blend:cl", "multisyllable", "position:begin"]),
      tok("crow", ["sentence", "blend:cr", "position:begin"]),
      tok("found", ["sentence", "position:end"]),
      tok("a", ["sentence", "sight"]),
      tok("jug"),
      tok("with", ["sentence", "sight"]),
      tok("a", ["sentence", "sight"]),
      tok("little", ["sentence", "multisyllable"]),
      tok("water", ["sentence", "multisyllable", "position:end"]),
      tok("It", ["sentence", "sight"]),
      tok("dropped", ["sentence", "blend:dr", "position:end"]),
      tok("small", ["sentence", "blend:sm"]),
      tok("stones", ["sentence", "blend:st", "position:begin"]),
      tok("in"),
      tok("and", ["sentence", "sight"]),
      tok("the", ["sentence", "sight"]),
      tok("water", ["sentence", "multisyllable"]),
      tok("rose"),
      tok("to", ["sentence", "sight"]),
      tok("the", ["sentence", "sight"]),
      tok("top", ["sentence", "position:end"]),
    ],
  },
  {
    id: "read-g3-garden",
    subject: "reading",
    grades: [3],
    category: "passage-reading",
    title: "The Community Garden",
    instruction: "Listen for longer words and whether the child keeps going through the middle and end of each word.",
    displayText:
      "Every Saturday, the neighbourhood children gather at the community garden to water vegetables and celebrate the harvest together.",
    titleHi: "सामुदायिक बगीचा",
    instructionHi:
      "लंबे शब्दों पर ध्यान दें और देखें कि बच्चा हर शब्द के बीच और अंत तक पढ़ पा रहा है या नहीं।",
    displayTextHi:
      "हर शनिवार पड़ोस के बच्चे सामुदायिक बगीचे में आते हैं। वे सब्ज़ियों को पानी देते हैं और साथ मिलकर फ़सल का जश्न मनाते हैं।",
    tokensHi: [
      tok("हर", ["sentence", "sight", "position:begin"]),
      tok("शनिवार", ["sentence", "multisyllable"]),
      tok("पड़ोस", ["sentence", "multisyllable", "position:begin"]),
      tok("के", ["sentence", "sight"]),
      tok("बच्चे", ["sentence", "multisyllable", "position:begin"]),
      tok("सामुदायिक", ["sentence", "multisyllable"]),
      tok("बगीचे", ["sentence", "multisyllable", "position:end"]),
      tok("में", ["sentence", "sight"]),
      tok("आते", ["sentence", "position:end"]),
      tok("हैं", ["sentence", "sight"]),
      tok("वे", ["sentence", "sight"]),
      tok("सब्ज़ियों", ["sentence", "multisyllable", "position:begin"]),
      tok("को", ["sentence", "sight"]),
      tok("पानी", ["sentence", "multisyllable"]),
      tok("देते", ["sentence", "position:end"]),
      tok("हैं", ["sentence", "sight"]),
      tok("और", ["sentence", "sight"]),
      tok("साथ", ["sentence", "position:end"]),
      tok("मिलकर", ["sentence", "multisyllable"]),
      tok("फ़सल", ["sentence", "multisyllable", "position:begin"]),
      tok("का", ["sentence", "sight"]),
      tok("जश्न", ["sentence", "multisyllable", "position:end"]),
      tok("मनाते", ["sentence", "multisyllable", "position:end"]),
      tok("हैं", ["sentence", "sight"]),
    ],
    tokens: [
      tok("Every", ["sentence", "multisyllable", "position:begin"]),
      tok("Saturday", ["sentence", "multisyllable"]),
      tok("the", ["sentence", "sight"]),
      tok("neighbourhood", ["sentence", "multisyllable"]),
      tok("children", ["sentence", "multisyllable", "blend:ch"]),
      tok("gather", ["sentence", "position:end"]),
      tok("at", ["sentence", "sight"]),
      tok("the", ["sentence", "sight"]),
      tok("community", ["sentence", "multisyllable"]),
      tok("garden", ["sentence", "multisyllable", "position:end"]),
      tok("to", ["sentence", "sight"]),
      tok("water", ["sentence", "multisyllable"]),
      tok("vegetables", ["sentence", "multisyllable"]),
      tok("and", ["sentence", "sight"]),
      tok("celebrate", ["sentence", "multisyllable", "blend:cl", "position:begin"]),
      tok("the", ["sentence", "sight"]),
      tok("harvest", ["sentence", "multisyllable", "position:end"]),
      tok("together", ["sentence", "multisyllable"]),
    ],
  },

  /* ── Oral Reading Fluency ───────────────────────────── */
  {
    id: "read-fluency-1",
    subject: "reading",
    grades: [2, 3],
    category: "oral-fluency",
    title: "One-minute read",
    instruction:
      "Ask the child to read aloud for one minute. Tap words that were wrong, skipped, or took a long pause.",
    displayText:
      "Tom and Ana play in the park. The sun is warm. Ana runs to the slide. Tom swings high. Rex barks at a ball. Mother calls them for lunch. They wave goodbye and walk home together.",
    tokens: [
      tok("Tom", ["fluency", "sentence", "position:begin"]),
      tok("and", ["fluency", "sentence", "sight"]),
      tok("Ana", ["fluency", "sentence", "position:begin"]),
      tok("play", ["fluency", "sentence", "word"]),
      tok("in", ["fluency", "sentence", "sight"]),
      tok("the", ["fluency", "sentence", "sight"]),
      tok("park", ["fluency", "sentence", "position:end"]),
      tok("The", ["fluency", "sentence", "sight"]),
      tok("sun", ["fluency", "sentence", "cvc"]),
      tok("is", ["fluency", "sentence", "sight"]),
      tok("warm", ["fluency", "sentence", "position:end"]),
      tok("Ana", ["fluency", "sentence"]),
      tok("runs", ["fluency", "sentence", "position:end"]),
      tok("to", ["fluency", "sentence", "sight"]),
      tok("the", ["fluency", "sentence", "sight"]),
      tok("slide", ["fluency", "sentence", "blend:sl", "position:end"]),
      tok("Tom", ["fluency", "sentence"]),
      tok("swings", ["fluency", "sentence", "blend:sw", "position:end"]),
      tok("high", ["fluency", "sentence", "position:end"]),
      tok("Rex", ["fluency", "sentence", "position:begin"]),
      tok("barks", ["fluency", "sentence", "position:end"]),
      tok("at", ["fluency", "sentence", "sight"]),
      tok("a", ["fluency", "sentence", "sight"]),
      tok("ball", ["fluency", "sentence", "position:end"]),
      tok("Mother", ["fluency", "sentence", "multisyllable", "position:begin"]),
      tok("calls", ["fluency", "sentence", "position:end"]),
      tok("them", ["fluency", "sentence", "sight"]),
      tok("for", ["fluency", "sentence", "sight"]),
      tok("lunch", ["fluency", "sentence", "position:end"]),
      tok("They", ["fluency", "sentence", "position:begin"]),
      tok("wave", ["fluency", "sentence", "position:end"]),
      tok("goodbye", ["fluency", "sentence", "multisyllable", "position:end"]),
      tok("and", ["fluency", "sentence", "sight"]),
      tok("walk", ["fluency", "sentence", "position:end"]),
      tok("home", ["fluency", "sentence"]),
      tok("together", ["fluency", "sentence", "multisyllable", "position:end"]),
    ],
    titleHi: "एक मिनट में पढ़ना",
    instructionHi:
      "बच्चे से एक मिनट तक ज़ोर से पढ़ने को कहें। जो शब्द गलत, छूटा या लंबी रुकावट वाला हो उसे टैप करें।",
    displayTextHi:
      "टॉम और आना बगीचे में खेलते हैं। धूप गरम है। आना फिसलपट्टी की ओर दौड़ती है। टॉम झूला झूलता है। एक गेंद पर कुत्ता भौंकता है। माँ उन्हें खाने के लिए बुलाती है। वे हाथ हिलाकर घर लौट जाते हैं।",
    tokensHi: [
      tok("टॉम", ["fluency", "sentence", "position:begin"]),
      tok("और", ["fluency", "sentence", "sight"]),
      tok("आना", ["fluency", "sentence", "position:begin"]),
      tok("बगीचे", ["fluency", "sentence", "multisyllable"]),
      tok("में", ["fluency", "sentence", "sight"]),
      tok("खेलते", ["fluency", "sentence", "position:end"]),
      tok("हैं", ["fluency", "sentence", "sight"]),
      tok("धूप", ["fluency", "sentence", "position:begin"]),
      tok("गरम", ["fluency", "sentence", "position:end"]),
      tok("है", ["fluency", "sentence", "sight"]),
      tok("आना", ["fluency", "sentence"]),
      tok("फिसलपट्टी", ["fluency", "sentence", "multisyllable"]),
      tok("की", ["fluency", "sentence", "sight"]),
      tok("ओर", ["fluency", "sentence", "sight"]),
      tok("दौड़ती", ["fluency", "sentence", "letter:d", "position:begin"]),
      tok("है", ["fluency", "sentence", "sight"]),
      tok("टॉम", ["fluency", "sentence"]),
      tok("झूला", ["fluency", "sentence", "position:begin"]),
      tok("झूलता", ["fluency", "sentence", "multisyllable", "position:end"]),
      tok("है", ["fluency", "sentence", "sight"]),
      tok("एक", ["fluency", "sentence", "sight"]),
      tok("गेंद", ["fluency", "sentence", "position:end"]),
      tok("पर", ["fluency", "sentence", "sight"]),
      tok("कुत्ता", ["fluency", "sentence", "multisyllable"]),
      tok("भौंकता", ["fluency", "sentence", "position:begin"]),
      tok("है", ["fluency", "sentence", "sight"]),
      tok("माँ", ["fluency", "sentence", "position:begin"]),
      tok("उन्हें", ["fluency", "sentence", "multisyllable"]),
      tok("खाने", ["fluency", "sentence", "position:begin"]),
      tok("के", ["fluency", "sentence", "sight"]),
      tok("लिए", ["fluency", "sentence", "position:end"]),
      tok("बुलाती", ["fluency", "sentence", "position:begin"]),
      tok("है", ["fluency", "sentence", "sight"]),
      tok("वे", ["fluency", "sentence", "sight"]),
      tok("हाथ", ["fluency", "sentence", "position:begin"]),
      tok("हिलाकर", ["fluency", "sentence", "multisyllable"]),
      tok("घर", ["fluency", "sentence", "position:end"]),
      tok("लौट", ["fluency", "sentence", "position:end"]),
      tok("जाते", ["fluency", "sentence", "position:end"]),
      tok("हैं", ["fluency", "sentence", "sight"]),
    ],
  },

  /* ══════════════════════ NUMERACY ══════════════════════ */

  /* ── Number Recognition ─────────────────────────────── */
  {
    id: "num-name-numbers",
    subject: "numeracy",
    grades: [1, 2],
    category: "number-recognition",
    title: "Name the numbers",
    instruction:
      "Point to each number and ask its name. Tap numbers that were wrong, skipped, or slow.",
    displayText: "4 9 12 17 25 30 41 58 63 77 89 92",
    tokens: [
      tok("4", ["number"]),
      tok("9", ["number"]),
      tok("12", ["number"]),
      tok("17", ["number"]),
      tok("25", ["number"]),
      tok("30", ["number", "decade", "decade:30"]),
      tok("41", ["number"]),
      tok("58", ["number"]),
      tok("63", ["number"]),
      tok("77", ["number"]),
      tok("89", ["number"]),
      tok("92", ["number"]),
    ],
    titleHi: "संख्याओं के नाम",
    instructionHi:
      "हर संख्या पर उँगली रखकर नाम पूछें। जो संख्या गलत, छूटी या देर से बोली जाए उसे टैप करें।",
  },

  /* ── Counting ───────────────────────────────────────── */
  {
    id: "num-g1-count-20",
    subject: "numeracy",
    grades: [1],
    category: "counting",
    title: "Count 1 to 20",
    instruction: "Ask the child to count from 1 to 20. Tap any number that was skipped, swapped, or needed a long pause.",
    displayText: "1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20",
    tokens: [
      tok("1", ["counting"]),
      tok("2", ["counting"]),
      tok("3", ["counting"]),
      tok("4", ["counting"]),
      tok("5", ["counting"]),
      tok("6", ["counting"]),
      tok("7", ["counting"]),
      tok("8", ["counting"]),
      tok("9", ["counting"]),
      tok("10", ["counting", "decade", "decade:10"]),
      tok("11", ["counting"]),
      tok("12", ["counting"]),
      tok("13", ["counting"]),
      tok("14", ["counting"]),
      tok("15", ["counting"]),
      tok("16", ["counting"]),
      tok("17", ["counting"]),
      tok("18", ["counting"]),
      tok("19", ["counting"]),
      tok("20", ["counting", "decade"]),
    ],
    titleHi: "1 से 20 तक गिनती",
    instructionHi:
      "बच्चे से 1 से 20 तक गिनने को कहें। जो संख्या छूटे, बदले या देर से बोली जाए उसे टैप करें।",
    displayTextHi:
      "एक दो तीन चार पाँच छह सात आठ नौ दस ग्यारह बारह तेरह चौदह पंद्रह सोलह सत्रह अठारह उन्नीस बीस",
    tokensHi: [
      tok("एक", ["counting"]),
      tok("दो", ["counting"]),
      tok("तीन", ["counting"]),
      tok("चार", ["counting"]),
      tok("पाँच", ["counting"]),
      tok("छह", ["counting"]),
      tok("सात", ["counting"]),
      tok("आठ", ["counting"]),
      tok("नौ", ["counting"]),
      tok("दस", ["counting", "decade", "decade:10"]),
      tok("ग्यारह", ["counting"]),
      tok("बारह", ["counting"]),
      tok("तेरह", ["counting"]),
      tok("चौदह", ["counting"]),
      tok("पंद्रह", ["counting"]),
      tok("सोलह", ["counting"]),
      tok("सत्रह", ["counting"]),
      tok("अठारह", ["counting"]),
      tok("उन्नीस", ["counting"]),
      tok("बीस", ["counting", "decade"]),
    ],
  },
  {
    id: "num-count-2",
    subject: "numeracy",
    grades: [2],
    category: "counting",
    title: "Count on from 21",
    instruction:
      "Ask the child to count aloud from 21 to 40. Tap any number that was skipped, swapped, or needed a long pause.",
    displayText: "21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40",
    tokens: [
      tok("21", ["counting"]),
      tok("22", ["counting"]),
      tok("23", ["counting"]),
      tok("24", ["counting"]),
      tok("25", ["counting"]),
      tok("26", ["counting"]),
      tok("27", ["counting"]),
      tok("28", ["counting"]),
      tok("29", ["counting"]),
      tok("30", ["counting", "decade", "decade:30"]),
      tok("31", ["counting"]),
      tok("32", ["counting"]),
      tok("33", ["counting"]),
      tok("34", ["counting"]),
      tok("35", ["counting"]),
      tok("36", ["counting"]),
      tok("37", ["counting"]),
      tok("38", ["counting"]),
      tok("39", ["counting"]),
      tok("40", ["counting", "decade"]),
    ],
    titleHi: "21 से आगे गिनो",
    instructionHi:
      "बच्चे से 21 से 40 तक ज़ोर से गिनने को कहें। जो संख्या छूटे, बदले या देर से बोली जाए उसे टैप करें।",
  },

  /* ── Number Sequencing ──────────────────────────────── */
  {
    id: "num-seq-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "number-sequencing",
    title: "What comes next?",
    instruction:
      "Ask the child to read the sequence and continue it. Tap numbers that were wrong, skipped, or paused on.",
    displayText: "2, 4, 6, 8, 10 · 11, 12, 13, 14, 15",
    tokens: [
      tok("2", ["sequence"]),
      tok("4", ["sequence"]),
      tok("6", ["sequence"]),
      tok("8", ["sequence"]),
      tok("10", ["sequence", "decade:10"]),
      tok("11", ["sequence"]),
      tok("12", ["sequence"]),
      tok("13", ["sequence"]),
      tok("14", ["sequence"]),
      tok("15", ["sequence"]),
    ],
    titleHi: "आगे क्या आता है?",
    instructionHi:
      "बच्चे से अनुक्रम पढ़कर जारी रखने को कहें। जो संख्या गलत, छूटी या रुककर बोली जाए उसे टैप करें।",
  },
  {
    id: "num-seq-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "number-sequencing",
    title: "Count on and back",
    instruction:
      "Ask the child to say each sequence aloud. Watch the jumps across the tens.",
    displayText: "25, 26, 27, 28, 29, 30, 31 · 40, 39, 38, 37, 36",
    tokens: [
      tok("25", ["sequence"]),
      tok("26", ["sequence"]),
      tok("27", ["sequence"]),
      tok("28", ["sequence"]),
      tok("29", ["sequence"]),
      tok("30", ["sequence", "decade", "decade:30"]),
      tok("31", ["sequence"]),
      tok("40", ["sequence", "decade"]),
      tok("39", ["sequence"]),
      tok("38", ["sequence"]),
      tok("37", ["sequence"]),
      tok("36", ["sequence"]),
    ],
    titleHi: "आगे और पीछे गिनो",
    instructionHi:
      "बच्चे से हर अनुक्रम ज़ोर से बोलने को कहें। दहाई पार करते समय ध्यान दें।",
  },
  {
    id: "num-g2-decades",
    subject: "numeracy",
    grades: [2],
    category: "number-sequencing",
    title: "Across the tens",
    instruction: "Ask the child to say the sequence. Watch especially around 29–30 and other ten-jumps.",
    displayText: "10, 20, 28, 29, 30, 31, 40, 58, 59, 60",
    tokens: [
      tok("10", ["sequence", "decade"]),
      tok("20", ["sequence", "decade"]),
      tok("28", ["sequence"]),
      tok("29", ["sequence"]),
      tok("30", ["sequence", "decade", "decade:30"]),
      tok("31", ["sequence"]),
      tok("40", ["sequence", "decade"]),
      tok("58", ["sequence"]),
      tok("59", ["sequence"]),
      tok("60", ["sequence", "decade"]),
    ],
    titleHi: "दहाई पार करना",
    instructionHi:
      "बच्चे से क्रम बोलने को कहें। 29–30 और अन्य दहाई-कूदों पर ख़ास ध्यान दें।",
    displayTextHi: "दस, बीस, अट्ठाईस, उनतीस, तीस, इकतीस, चालीस, अट्ठावन, उनसठ, साठ",
    tokensHi: [
      tok("दस", ["sequence", "decade"]),
      tok("बीस", ["sequence", "decade"]),
      tok("अट्ठाईस", ["sequence"]),
      tok("उनतीस", ["sequence"]),
      tok("तीस", ["sequence", "decade", "decade:30"]),
      tok("इकतीस", ["sequence"]),
      tok("चालीस", ["sequence", "decade"]),
      tok("अट्ठावन", ["sequence"]),
      tok("उनसठ", ["sequence"]),
      tok("साठ", ["sequence", "decade"]),
    ],
  },
  {
    id: "num-g2-backward",
    subject: "numeracy",
    grades: [2],
    category: "number-sequencing",
    title: "Count backward from 20",
    instruction: "Ask the child to count backward from 20 to 10. Mark slips or long pauses.",
    displayText: "20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10",
    tokens: [
      tok("20", ["sequence", "backward", "decade"]),
      tok("19", ["sequence", "backward"]),
      tok("18", ["sequence", "backward"]),
      tok("17", ["sequence", "backward"]),
      tok("16", ["sequence", "backward"]),
      tok("15", ["sequence", "backward"]),
      tok("14", ["sequence", "backward"]),
      tok("13", ["sequence", "backward"]),
      tok("12", ["sequence", "backward"]),
      tok("11", ["sequence", "backward"]),
      tok("10", ["sequence", "backward", "decade", "decade:10"]),
    ],
    titleHi: "20 से उल्टी गिनती",
    instructionHi:
      "बच्चे से 20 से 10 तक उल्टी गिनती करने को कहें। फिसलन या लंबी रुकावट को चिह्नित करें।",
    displayTextHi: "बीस, उन्नीस, अठारह, सत्रह, सोलह, पंद्रह, चौदह, तेरह, बारह, ग्यारह, दस",
    tokensHi: [
      tok("बीस", ["sequence", "backward", "decade"]),
      tok("उन्नीस", ["sequence", "backward"]),
      tok("अठारह", ["sequence", "backward"]),
      tok("सत्रह", ["sequence", "backward"]),
      tok("सोलह", ["sequence", "backward"]),
      tok("पंद्रह", ["sequence", "backward"]),
      tok("चौदह", ["sequence", "backward"]),
      tok("तेरह", ["sequence", "backward"]),
      tok("बारह", ["sequence", "backward"]),
      tok("ग्यारह", ["sequence", "backward"]),
      tok("दस", ["sequence", "backward", "decade", "decade:10"]),
    ],
  },

  /* ── Before / After Numbers ─────────────────────────── */
  {
    id: "num-before-after-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "before-after",
    title: "Before and after",
    instruction:
      "Ask what comes just before and just after each number. Mark slips or pauses.",
    displayText: "before 7 · after 7 · before 12 · after 12 · before 30 · after 30",
    tokens: [
      tok("before 7", ["before-after"]),
      tok("after 7", ["before-after"]),
      tok("before 12", ["before-after"]),
      tok("after 12", ["before-after"]),
      tok("before 30", ["before-after", "decade:30"]),
      tok("after 30", ["before-after", "decade:30"]),
    ],
    titleHi: "पहले और बाद",
    instructionHi:
      "हर संख्या से ठीक पहले और ठीक बाद आने वाली संख्या पूछें। फिसलन या रुकावट चिह्नित करें।",
  },

  /* ── Number Comparison ──────────────────────────────── */
  {
    id: "num-compare-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "number-comparison",
    title: "Bigger or smaller?",
    instruction:
      "Ask which number is bigger in each pair. Tap pairs answered wrong or with a long pause.",
    displayText: "7 or 9 · 15 or 12 · 20 or 19 · 34 or 43",
    tokens: [
      tok("7 or 9", ["compare"]),
      tok("15 or 12", ["compare"]),
      tok("20 or 19", ["compare", "decade"]),
      tok("34 or 43", ["compare", "place-value"]),
    ],
    titleHi: "बड़ा या छोटा?",
    instructionHi:
      "हर जोड़े में पूछें कि कौन सी संख्या बड़ी है। गलत या लंबी रुकावट वाले जोड़े टैप करें।",
  },
  {
    id: "num-compare-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "number-comparison",
    title: "Compare three-digit numbers",
    instruction: "Ask which number is bigger. Mark wrong comparisons or long pauses.",
    displayText: "108 or 180 · 245 or 254 · 399 or 401 · 500 or 499",
    tokens: [
      tok("108 or 180", ["compare", "place-value"]),
      tok("245 or 254", ["compare", "place-value"]),
      tok("399 or 401", ["compare", "place-value"]),
      tok("500 or 499", ["compare", "place-value", "decade"]),
    ],
    titleHi: "तीन अंकों की संख्याओं की तुलना",
    instructionHi: "पूछें कि कौन सी संख्या बड़ी है। गलत तुलना या लंबी रुकावट चिह्नित करें।",
  },

  /* ── Tens and Ones ──────────────────────────────────── */
  {
    id: "num-tens-ones-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "tens-ones",
    title: "Tens and ones",
    instruction:
      "Ask how many tens and how many ones are in each number. Mark errors.",
    displayText: "13 · 25 · 40 · 67 · 92",
    tokens: [
      tok("13", ["tens-ones", "place-value"]),
      tok("25", ["tens-ones", "place-value"]),
      tok("40", ["tens-ones", "place-value", "decade"]),
      tok("67", ["tens-ones", "place-value"]),
      tok("92", ["tens-ones", "place-value"]),
    ],
    titleHi: "दहाई और इकाई",
    instructionHi:
      "हर संख्या में कितनी दहाई और कितनी इकाई हैं, पूछें। गलतियाँ चिह्नित करें।",
  },

  /* ── Place Value ────────────────────────────────────── */
  {
    id: "num-place-2",
    subject: "numeracy",
    grades: [2],
    category: "place-value",
    title: "Say the number",
    instruction:
      "Ask the child to read each number aloud. Mark numbers named with the wrong place value.",
    displayText: "45 · 32 · 71 · 60 · 84",
    tokens: [
      tok("45", ["place-value"]),
      tok("32", ["place-value"]),
      tok("71", ["place-value"]),
      tok("60", ["place-value", "decade"]),
      tok("84", ["place-value"]),
    ],
    titleHi: "संख्या बोलो",
    instructionHi:
      "बच्चे से हर संख्या ज़ोर से पढ़ने को कहें। गलत स्थानीय मान से बोली गई संख्या चिह्नित करें।",
  },
  {
    id: "num-g3-place",
    subject: "numeracy",
    grades: [3],
    category: "place-value",
    title: "Three-digit numbers",
    instruction: "Ask the child to read each number aloud. Mark any number named with the wrong place value.",
    displayText: "108, 199, 200, 245, 350, 499, 500",
    tokens: [
      tok("108", ["place-value"]),
      tok("199", ["place-value"]),
      tok("200", ["place-value", "decade"]),
      tok("245", ["place-value"]),
      tok("350", ["place-value"]),
      tok("499", ["place-value"]),
      tok("500", ["place-value", "decade"]),
    ],
    titleHi: "तीन अंकों वाली संख्याएँ",
    instructionHi:
      "बच्चे से प्रत्येक संख्या ज़ोर से पढ़ने को कहें। जो संख्या गलत स्थानीय मान से बोली जाए उसे चिह्नित करें।",
    displayTextHi:
      "एक सौ आठ, एक सौ निन्यानवे, दो सौ, दो सौ पैंतालीस, तीन सौ पचास, चार सौ निन्यानवे, पाँच सौ",
    tokensHi: [
      tok("एक सौ आठ", ["place-value"]),
      tok("एक सौ निन्यानवे", ["place-value"]),
      tok("दो सौ", ["place-value", "decade"]),
      tok("दो सौ पैंतालीस", ["place-value"]),
      tok("तीन सौ पचास", ["place-value"]),
      tok("चार सौ निन्यानवे", ["place-value"]),
      tok("पाँच सौ", ["place-value", "decade"]),
    ],
  },

  /* ── Addition ───────────────────────────────────────── */
  {
    id: "num-add-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "addition",
    title: "Add these",
    instruction:
      "Ask the child to solve each sum aloud. Tap sums that were wrong or needed a long pause.",
    displayText: "2 + 3 · 4 + 4 · 5 + 6 · 7 + 8 · 9 + 9",
    tokens: [
      tok("2 + 3", ["addition"]),
      tok("4 + 4", ["addition"]),
      tok("5 + 6", ["addition"]),
      tok("7 + 8", ["addition"]),
      tok("9 + 9", ["addition"]),
    ],
    titleHi: "इन्हें जोड़ो",
    instructionHi:
      "बच्चे से हर सवाल हल करके बोलने को कहें। गलत या लंबी रुकावट वाले सवाल टैप करें।",
  },
  {
    id: "num-add-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "addition",
    title: "Add larger numbers",
    instruction:
      "Ask the child to solve each sum aloud. Tap sums with a wrong answer or a long pause.",
    displayText: "13 + 5 · 24 + 10 · 35 + 27 · 48 + 19",
    tokens: [
      tok("13 + 5", ["addition", "place-value"]),
      tok("24 + 10", ["addition", "place-value"]),
      tok("35 + 27", ["addition", "place-value"]),
      tok("48 + 19", ["addition", "place-value"]),
    ],
    titleHi: "बड़ी संख्याएँ जोड़ो",
    instructionHi:
      "बच्चे से हर सवाल हल करके बोलने को कहें। गलत उत्तर या लंबी रुकावट वाले सवाल टैप करें।",
  },

  /* ── Subtraction ────────────────────────────────────── */
  {
    id: "num-sub-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "subtraction",
    title: "Take away",
    instruction:
      "Ask the child to solve each subtraction aloud. Tap sums that were wrong or slow.",
    displayText: "5 − 2 · 9 − 4 · 10 − 6 · 12 − 7 · 15 − 8",
    tokens: [
      tok("5 − 2", ["subtraction"]),
      tok("9 − 4", ["subtraction"]),
      tok("10 − 6", ["subtraction", "decade:10"]),
      tok("12 − 7", ["subtraction"]),
      tok("15 − 8", ["subtraction"]),
    ],
    titleHi: "घटाओ",
    instructionHi:
      "बच्चे से हर घटाव हल करके बोलने को कहें। गलत या धीमे सवाल टैप करें।",
  },
  {
    id: "num-sub-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "subtraction",
    title: "Subtract larger numbers",
    instruction:
      "Ask the child to solve each subtraction aloud. Mark wrong answers or long pauses.",
    displayText: "20 − 8 · 34 − 12 · 50 − 27 · 63 − 38",
    tokens: [
      tok("20 − 8", ["subtraction", "place-value", "decade"]),
      tok("34 − 12", ["subtraction", "place-value"]),
      tok("50 − 27", ["subtraction", "place-value", "decade"]),
      tok("63 − 38", ["subtraction", "place-value"]),
    ],
    titleHi: "बड़ी संख्याएँ घटाओ",
    instructionHi:
      "बच्चे से हर घटाव हल करके बोलने को कहें। गलत उत्तर या लंबी रुकावट चिह्नित करें।",
  },

  /* ── Number Bonds ───────────────────────────────────── */
  {
    id: "num-bonds-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "number-bonds",
    title: "Bonds to 10",
    instruction:
      "Ask the child to say the missing number that makes 10. Tap wrong or slow answers.",
    displayText: "1 + ? = 10 · 3 + ? = 10 · 6 + ? = 10 · 8 + ? = 10",
    tokens: [
      tok("1 + ? = 10", ["bonds", "addition"]),
      tok("3 + ? = 10", ["bonds", "addition"]),
      tok("6 + ? = 10", ["bonds", "addition"]),
      tok("8 + ? = 10", ["bonds", "addition"]),
    ],
    titleHi: "10 के जोड़े",
    instructionHi:
      "बच्चे से वह संख्या बताने को कहें जो मिलकर 10 बनाए। गलत या धीमे उत्तर टैप करें।",
  },
  {
    id: "num-bonds-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "number-bonds",
    title: "Bonds to 20, 30, 50",
    instruction: "Ask the child to say the missing number. Mark wrong answers.",
    displayText: "? + 7 = 20 · 12 + ? = 20 · ? + 15 = 30 · 25 + ? = 50",
    tokens: [
      tok("? + 7 = 20", ["bonds", "addition", "place-value"]),
      tok("12 + ? = 20", ["bonds", "addition", "place-value"]),
      tok("? + 15 = 30", ["bonds", "addition", "place-value"]),
      tok("25 + ? = 50", ["bonds", "addition", "place-value"]),
    ],
    titleHi: "20, 30, 50 के जोड़े",
    instructionHi: "बच्चे से लुप्त संख्या बताने को कहें। गलत उत्तर चिह्नित करें।",
  },

  /* ── Skip Counting ──────────────────────────────────── */
  {
    id: "num-skip-1",
    subject: "numeracy",
    grades: [1, 2],
    category: "skip-counting",
    title: "Skip count: 2s and 5s",
    instruction:
      "Ask the child to count by 2s and by 5s. Tap numbers that were skipped, swapped, or paused on.",
    displayText: "2, 4, 6, 8, 10 · 5, 10, 15, 20, 25",
    tokens: [
      tok("2", ["skip"]),
      tok("4", ["skip"]),
      tok("6", ["skip"]),
      tok("8", ["skip"]),
      tok("10", ["skip", "decade:10"]),
      tok("5", ["skip"]),
      tok("10", ["skip", "decade:10"]),
      tok("15", ["skip"]),
      tok("20", ["skip", "decade"]),
      tok("25", ["skip"]),
    ],
    titleHi: "छलाँग गिनती: 2 और 5",
    instructionHi:
      "बच्चे से 2 की और 5 की छलाँग में गिनने को कहें। जो संख्या छूटे, बदले या रुके उसे टैप करें।",
  },
  {
    id: "num-skip-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "skip-counting",
    title: "Skip count: 10s and 5s",
    instruction:
      "Ask the child to count by 10s and by 5s from 45. Mark slips.",
    displayText: "10, 20, 30, 40, 50 · 45, 50, 55, 60, 65",
    tokens: [
      tok("10", ["skip", "decade"]),
      tok("20", ["skip", "decade"]),
      tok("30", ["skip", "decade"]),
      tok("40", ["skip", "decade"]),
      tok("50", ["skip", "decade"]),
      tok("45", ["skip"]),
      tok("50", ["skip"]),
      tok("55", ["skip"]),
      tok("60", ["skip", "decade"]),
      tok("65", ["skip"]),
    ],
    titleHi: "छलाँग गिनती: 10 और 5",
    instructionHi:
      "बच्चे से 10 की छलाँग में और 45 से 5 की छलाँग में गिनने को कहें। फिसलन चिह्नित करें।",
  },

  /* ── Simple Word Problems ───────────────────────────── */
  {
    id: "num-wordprob-1",
    subject: "numeracy",
    grades: [2, 3],
    category: "word-problems",
    title: "Story sums: adding",
    instruction:
      "Read the story, then ask the child for the answer. Tap the parts that were wrong or skipped.",
    displayText: "Rita has 3 apples. She gets 2 more. How many now?",
    tokens: [
      tok("3", ["word-problem", "addition"]),
      tok("2", ["word-problem", "addition"]),
      tok("5", ["word-problem", "addition"]),
    ],
    titleHi: "कहानी वाले सवाल: जोड़",
    instructionHi:
      "कहानी पढ़ें, फिर बच्चे से उत्तर पूछें। जो हिस्सा गलत या छूटा हो उसे टैप करें।",
    displayTextHi: "रीता के पास 3 सेब हैं। उसे 2 और मिले। अब कितने हैं?",
  },
  {
    id: "num-wordprob-2",
    subject: "numeracy",
    grades: [2, 3],
    category: "word-problems",
    title: "Story sums: taking away",
    instruction:
      "Read the story, then ask the child for the answer. Tap the parts that were wrong or skipped.",
    displayText: "8 children are on a bus. 3 get off. How many are left?",
    tokens: [
      tok("8", ["word-problem", "subtraction"]),
      tok("3", ["word-problem", "subtraction"]),
      tok("5", ["word-problem", "subtraction"]),
    ],
    titleHi: "कहानी वाले सवाल: घटाव",
    instructionHi:
      "कहानी पढ़ें, फिर बच्चे से उत्तर पूछें। जो हिस्सा गलत या छूटा हो उसे टैप करें।",
    displayTextHi: "एक बस में 8 बच्चे हैं। 3 उतर जाते हैं। कितने बचे?",
  },
];

export function getPrompt(id: string): AssessmentPrompt | undefined {
  return ASSESSMENT_PROMPTS.find((p) => p.id === id);
}

export function promptsFor(
  subject: Subject,
  grade: Grade,
  category?: string,
): AssessmentPrompt[] {
  return ASSESSMENT_PROMPTS.filter(
    (p) =>
      p.subject === subject &&
      p.grades.includes(grade) &&
      (category === undefined || p.category === category),
  );
}

export function defaultPrompt(subject: Subject, grade: Grade): AssessmentPrompt {
  return promptsFor(subject, grade)[0];
}