import type { Grade, Subject, WorksheetTemplate, WorksheetTier } from "./types";

export const WORKSHEET_TEMPLATES: WorksheetTemplate[] = [
  {
    id: "ws-bd-1",
    gapTypeId: "letter-sound-bd",
    subject: "reading",
    grades: [1, 2],
    tier: 1,
    title: "b and d sound sort",
    focus: "Hear, trace, and sort short b/d words with picture support.",
    items: [
      { prompt: "Circle the letter that matches the picture: ball / doll." },
      { prompt: "Say: bat, bag, bed. Trace b three times." },
      { prompt: "Say: dog, dig, lid. Trace d three times." },
      { prompt: "Sort: bad, dad, big, dig — b-words vs d-words." },
    ],
    titleHi: "ब और द ध्वनि क्रमबद्ध",
    focusHi: "चित्र की मदद से छोटे ब/द शब्द सुनो, लिखो और छाँटो।",
    itemsHi: [
      { prompt: "चित्र से मिलते अक्षर पर गोला लगाओ: गेंद / गुड़िया।" },
      { prompt: "बोलो: बकरी, बंदर, बिल्ली। 'ब' तीन बार लिखो।" },
      { prompt: "बोलो: दरवाज़ा, दादा, दूध। 'द' तीन बार लिखो।" },
      { prompt: "छाँटो: बग, बिल्ली, दग, दाद — 'ब' शब्द अलग, 'द' शब्द अलग।" },
    ],
  },
  {
    id: "ws-bd-2",
    gapTypeId: "letter-sound-bd",
    subject: "reading",
    grades: [1, 2],
    tier: 2,
    title: "b and d in sentences",
    focus: "Read short sentences that mix b and d without relying on pictures.",
    items: [
      { prompt: "Read: The dog sat on the bed." },
      { prompt: "Read: Dad had a big bag." },
      { prompt: "Write b or d: _og, _ed, _ad, _ig." },
      { prompt: "Make two new words with b and two with d." },
    ],
    titleHi: "वाक्यों में ब और द",
    focusHi: "बिना चित्र के ब और द मिले छोटे वाक्य पढ़ो।",
    itemsHi: [
      { prompt: "पढ़ो: दादा के पास एक बिल्ली है।" },
      { prompt: "पढ़ो: बंदर दूध पीता है।" },
      { prompt: "खाली जगह भरो: _िल्ली, _ादा, _ूध, _करी।" },
      { prompt: "'ब' से दो और 'द' से दो नए शब्द बनाओ।" },
    ],
  },
  {
    id: "ws-blend-1",
    gapTypeId: "consonant-blend-bl-cl-st",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 1,
    title: "Blend builders: bl · cl · st",
    focus: "Stretch and blend the two starting sounds before reading the word.",
    items: [
      { prompt: "Stretch: b-l-ue → blue. Clap the two starting sounds." },
      { prompt: "Stretch: c-l-ap → clap." },
      { prompt: "Stretch: s-t-op → stop." },
      { prompt: "Picture match: block, clock, star." },
    ],
    titleHi: "संयुक्त व्यंजन निर्माण: क्ल · प्ल · स्ट",
    focusHi: "शुरुआती दो ध्वनियाँ खींचकर मिलाओ, फिर पूरा शब्द पढ़ो।",
    itemsHi: [
      { prompt: "खींचो: क-ल-ास → क्लास। दो शुरुआती ध्वनियाँ ताली से बजाओ।" },
      { prompt: "खींचो: प-ल-ेट → प्लेट।" },
      { prompt: "खींचो: स-ट-ेशन → स्टेशन।" },
      { prompt: "चित्र मिलाओ: क्लास, प्लेट, स्टार।" },
    ],
  },
  {
    id: "ws-blend-2",
    gapTypeId: "consonant-blend-bl-cl-st",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 2,
    title: "Blend sentences: bl · cl · st",
    focus: "Keep both consonants when the blend sits inside a short sentence.",
    items: [
      { prompt: "Read: The black cat sat on the mat." },
      { prompt: "Read: Clap for the class." },
      { prompt: "Read: Stop at the stone step." },
      { prompt: "Write three words: one bl, one cl, one st." },
    ],
    titleHi: "संयुक्त व्यंजन वाक्य: क्ल · प्ल · स्ट",
    focusHi: "छोटे वाक्यों में संयुक्त व्यंजन बनाए रखो।",
    itemsHi: [
      { prompt: "पढ़ो: क्लास में सब चुप हैं।" },
      { prompt: "पढ़ो: प्लेट पर प्लम है।" },
      { prompt: "पढ़ो: रेल स्टेशन पर भीड़ है।" },
      { prompt: "तीन शब्द लिखो: एक क्ल, एक प्ल, एक स्ट से।" },
    ],
  },
  {
    id: "ws-blend-3",
    gapTypeId: "consonant-blend-bl-cl-st",
    subject: "reading",
    grades: [2, 3],
    tier: 3,
    title: "Blend story strip",
    focus: "Read a short connected text packed with target blends.",
    items: [
      {
        prompt:
          "Read: Stan and Clare stop at the black stone. Clare claps. Stan stands still.",
      },
      { prompt: "Underline every bl, cl, and st you hear." },
      { prompt: "Retell the strip in your own words." },
    ],
    titleHi: "संयुक्त व्यंजन कहानी-पट्टी",
    focusHi: "संयुक्त व्यंजनों से भरा छोटा गद्यांश पढ़ो।",
    itemsHi: [
      {
        prompt: "पढ़ो: स्टेशन के पास एक क्लास है। बच्चे प्लेट पर प्लम रखते हैं।",
      },
      { prompt: "जहाँ क्ल, प्ल, स्ट सुनो वहाँ रेखा खींचो।" },
      { prompt: "पट्टी अपने शब्दों में दोबारा सुनाओ।" },
    ],
  },
  {
    id: "ws-begin-1",
    gapTypeId: "word-position-begin",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 1,
    title: "First-sound spotlight",
    focus: "Slow down on the first sound before saying the rest of the word.",
    items: [
      { prompt: "Tap the first sound: m-at, s-un, t-op." },
      { prompt: "Cover the rest of the word. Say only the first sound, then the whole word." },
      { prompt: "Read: mat, sun, top, dog, cat." },
    ],
    titleHi: "पहली ध्वनि की रोशनी",
    focusHi: "पूरा शब्द बोलने से पहले पहली ध्वनि पर धीरे रुको।",
    itemsHi: [
      { prompt: "पहली ध्वनि टैप करो: म-छली, स-ड़क, त-रबूज़।" },
      { prompt: "शब्द का बाकी हिस्सा ढक दो। पहले सिर्फ पहली ध्वनि, फिर पूरा शब्द बोलो।" },
      { prompt: "पढ़ो: मछली, सड़क, तरबूज़, दरवाज़ा, किताब।" },
    ],
  },
  {
    id: "ws-end-1",
    gapTypeId: "word-position-end",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 1,
    title: "Last-sound listen",
    focus: "Hold the last sound so it is not dropped.",
    items: [
      { prompt: "Stretch the last sound: ru-n, na-p, si-t." },
      { prompt: "Which word ends with t: cat, can, cap?" },
      { prompt: "Read and clap the last sound: hop, hat, hen." },
    ],
    titleHi: "अंतिम ध्वनि सुनो",
    focusHi: "अंतिम ध्वनि पकड़कर रखो ताकि वह छूटे नहीं।",
    itemsHi: [
      { prompt: "अंतिम ध्वनि खींचो: का-म, न-मक, हा-थ।" },
      { prompt: "किस शब्द के अंत में 'त' है: रात, राम, राज?" },
      { prompt: "पढ़ो और अंतिम ध्वनि पर ताली बजाओ: होठ, मात, बात।" },
    ],
  },
  {
    id: "ws-sight-1",
    gapTypeId: "sight-word-recall",
    subject: "reading",
    grades: [1, 2],
    tier: 1,
    title: "Everyday words flash sheet",
    focus: "See the whole word: the, and, can, I, to, a.",
    items: [
      { prompt: "Flash: the, and, can, I, to, a (3 times each)." },
      { prompt: "Find them in: The cat and I can sit." },
      { prompt: "Write: the, and, can." },
    ],
    titleHi: "रोज़ के शब्दों की फ्लैश शीट",
    focusHi: "पूरा शब्द देखो: का, की, और, मैं, है, नहीं।",
    itemsHi: [
      { prompt: "फ्लैश: का, की, और, मैं, है, नहीं (प्रत्येक 3 बार)।" },
      { prompt: "इन्हें ढूँढो: मैं और माँ बाज़ार जाते हैं।" },
      { prompt: "लिखो: का, की, और।" },
    ],
  },
  {
    id: "ws-sight-2",
    gapTypeId: "sight-word-recall",
    subject: "reading",
    grades: [1, 2],
    tier: 2,
    title: "Sight words in a tiny story",
    focus: "Read connected text without sounding each letter of known words.",
    items: [
      { prompt: "Read: I can sit and the dog can nap." },
      { prompt: "Cover and recall: the, and, can." },
      { prompt: "Write one new sentence using the, and, can." },
    ],
    titleHi: "छोटी कहानी में दृष्टि-शब्द",
    focusHi: "जाने-पहचाने शब्दों को अक्षर-अक्षर किए बिना पढ़ो।",
    itemsHi: [
      { prompt: "पढ़ो: मैं और दादा सुबह टहलते हैं।" },
      { prompt: "ढककर याद करो: मैं, और, हैं।" },
      { prompt: "'मैं', 'और', 'है' से एक नया वाक्य लिखो।" },
    ],
  },
  {
    id: "ws-multi-1",
    gapTypeId: "multisyllable-decoding",
    subject: "reading",
    grades: [2, 3],
    tier: 1,
    title: "Syllable break-up cards",
    focus: "Clap and chunk longer words before reading them.",
    items: [
      { prompt: "Clap: wa-ter, gar-den, Sat-ur-day." },
      { prompt: "Read each chunk, then the whole word." },
      { prompt: "Circle the number of claps in: community, vegetables, together." },
    ],
    titleHi: "अक्षर-विभाजन कार्ड",
    focusHi: "लंबे शब्द पढ़ने से पहले ताली बजाकर टुकड़े करो।",
    itemsHi: [
      { prompt: "ताली बजाओ: सा-मु-दा-यिक, प-ड़ो-सी, श-नि-वार।" },
      { prompt: "हर टुकड़ा पढ़ो, फिर पूरा शब्द।" },
      { prompt: "तालियों की संख्या पर गोला लगाओ: सब्ज़ियाँ, फ़सल, जश्न।" },
    ],
  },
  {
    id: "ws-multi-2",
    gapTypeId: "multisyllable-decoding",
    subject: "reading",
    grades: [2, 3],
    tier: 2,
    title: "Chunk and reread",
    focus: "Reread a short paragraph after marking syllable breaks.",
    items: [
      { prompt: "Mark breaks in: neighbourhood, celebrate, harvest." },
      { prompt: "Read the garden paragraph slowly, then a little faster." },
      { prompt: "Tell a partner what the children did on Saturday." },
    ],
    titleHi: "टुकड़ा करो और दोबारा पढ़ो",
    focusHi: "अक्षर-विभाजन चिह्नित करने के बाद छोटा पैराग्राफ दोबारा पढ़ो।",
    itemsHi: [
      { prompt: "इनमें टुकड़े चिह्नित करो: पड़ोस, सामुदायिक, शनिवार।" },
      { prompt: "बगीचे का पैराग्राफ धीरे पढ़ो, फिर थोड़ा तेज़।" },
      { prompt: "साथी को बताओ कि बच्चों ने शनिवार को क्या किया।" },
    ],
  },
  {
    id: "ws-dec10-1",
    gapTypeId: "decade-9-10",
    subject: "numeracy",
    grades: [1, 2],
    tier: 1,
    title: "Crossing to 10",
    focus: "Count objects across the 9-to-10 boundary with a ten-frame.",
    items: [
      { prompt: "Fill a ten-frame: 8, 9, 10. Say each number." },
      { prompt: "Count 9 pebbles, add 1. What number now?" },
      { prompt: "Write the path: 7  8  9  __  11." },
    ],
    titleHi: "10 पार करना",
    focusHi: "टेन-फ्रेम से 9 से 10 की सीमा पार करके गिनो।",
    itemsHi: [
      { prompt: "टेन-फ्रेम भरो: 8, 9, 10। हर संख्या बोलो।" },
      { prompt: "9 कंकड़ गिनो, 1 और जोड़ो। अब कितने?" },
      { prompt: "रास्ता लिखो: 7  8  9  __  11।" },
    ],
  },
  {
    id: "ws-dec10-2",
    gapTypeId: "decade-9-10",
    subject: "numeracy",
    grades: [1, 2],
    tier: 2,
    title: "Ten-jumps with a number path",
    focus: "Move on a number path from 8 through 12 without skipping 10.",
    items: [
      { prompt: "Hop on the path: 8 → 9 → 10 → 11 → 12." },
      { prompt: "Start at 9. Add 1 three times. Write the numbers." },
      { prompt: "Circle every 10 you land on while counting to 20." },
    ],
    titleHi: "संख्या-पथ पर दस की छलाँग",
    focusHi: "संख्या-पथ पर 8 से 12 तक चलो, 10 को छोड़े बिना।",
    itemsHi: [
      { prompt: "पथ पर कूदो: 8 → 9 → 10 → 11 → 12।" },
      { prompt: "9 से शुरू करो। 1 तीन बार जोड़ो। संख्याएँ लिखो।" },
      { prompt: "20 तक गिनते हुए हर 10 पर गोला लगाओ।" },
    ],
  },
  {
    id: "ws-dec30-1",
    gapTypeId: "decade-29-30",
    subject: "numeracy",
    grades: [2, 3],
    tier: 1,
    title: "Decade jump: 29 → 30",
    focus: "Practise the tens change from 29 to 30 with a hundred chart.",
    items: [
      { prompt: "Say: 27, 28, 29, 30, 31. Tap 30 in a louder voice." },
      { prompt: "Colour 29 and 30 on a hundred chart." },
      { prompt: "Fill: 28, __, 30, __." },
    ],
    titleHi: "दहाई छलाँग: 29 → 30",
    focusHi: "सौ-चार्ट से 29 से 30 की दहाई बदलाव का अभ्यास करो।",
    itemsHi: [
      { prompt: "बोलो: 27, 28, 29, 30, 31। 30 पर तेज़ आवाज़ में टैप करो।" },
      { prompt: "सौ-चार्ट पर 29 और 30 रंगो।" },
      { prompt: "भरो: 28, __, 30, __।" },
    ],
  },
  {
    id: "ws-dec30-2",
    gapTypeId: "decade-29-30",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "More decade jumps to 100",
    focus: "Repeat the 29–30 pattern at 39–40, 59–60, and 79–80.",
    items: [
      { prompt: "Fill: 38, 39, __, 41." },
      { prompt: "Fill: 58, 59, __, 61." },
      { prompt: "Fill: 78, 79, __, 81." },
      { prompt: "Tell a friend what changes when you go from 29 to 30." },
    ],
    titleHi: "100 तक और दहाई छलाँगें",
    focusHi: "39–40, 59–60 और 79–80 पर भी 29–30 वाला पैटर्न दोहराओ।",
    itemsHi: [
      { prompt: "भरो: 38, 39, __, 41।" },
      { prompt: "भरो: 58, 59, __, 61।" },
      { prompt: "भरो: 78, 79, __, 81।" },
      { prompt: "साथी को बताओ कि 29 से 30 जाते समय क्या बदलता है।" },
    ],
  },
  {
    id: "ws-dec30-3",
    gapTypeId: "decade-29-30",
    subject: "numeracy",
    grades: [2, 3],
    tier: 3,
    title: "Mixed decade crossings",
    focus: "Count forward and backward across several decade boundaries.",
    items: [
      { prompt: "Count forward: 25 to 35." },
      { prompt: "Count backward: 42 to 28." },
      { prompt: "Circle every number where the tens digit changes." },
    ],
    titleHi: "मिली-जुली दहाई पार करना",
    focusHi: "कई दहाई सीमाओं पर आगे-पीछे गिनो।",
    itemsHi: [
      { prompt: "आगे गिनो: 25 से 35 तक।" },
      { prompt: "उल्टा गिनो: 42 से 28 तक।" },
      { prompt: "जहाँ दहाई का अंक बदले वहाँ गोला लगाओ।" },
    ],
  },
  {
    id: "ws-decade-1",
    gapTypeId: "decade-generic",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Next ten practice",
    focus: "Name the next ten after 10, 20, 40, and 60.",
    items: [
      { prompt: "What comes after 19?" },
      { prompt: "What comes after 39?" },
      { prompt: "Hop: 10, 20, 30, __, 50." },
    ],
    titleHi: "अगली दहाई का अभ्यास",
    focusHi: "10, 20, 40 और 60 के बाद की दहाई बताओ।",
    itemsHi: [
      { prompt: "19 के बाद क्या आता है?" },
      { prompt: "39 के बाद क्या आता है?" },
      { prompt: "कूदो: 10, 20, 30, __, 50।" },
    ],
  },
  {
    id: "ws-place-1",
    gapTypeId: "place-value-tens-hundreds",
    subject: "numeracy",
    grades: [2, 3],
    tier: 1,
    title: "Hundreds, tens, ones grid",
    focus: "Build 3-digit numbers with place-value blocks or drawings.",
    items: [
      { prompt: "Show 245: how many hundreds, tens, ones?" },
      { prompt: "Which is more: 199 or 200? Why?" },
      { prompt: "Write the number: 3 hundreds, 5 tens, 0 ones." },
    ],
    titleHi: "सैकड़ा, दहाई, इकाई ग्रिड",
    focusHi: "स्थानीय मान वाले ब्लॉक या चित्र से तीन अंकों की संख्याएँ बनाओ।",
    itemsHi: [
      { prompt: "245 दिखाओ: कितने सैकड़े, कितनी दहाई, कितनी इकाई?" },
      { prompt: "कौन बड़ी है: 199 या 200? क्यों?" },
      { prompt: "संख्या लिखो: 3 सैकड़े, 5 दहाई, 0 इकाई।" },
    ],
  },
  {
    id: "ws-place-2",
    gapTypeId: "place-value-tens-hundreds",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Read and build 3-digit numbers",
    focus: "Read numbers aloud and rebuild them if a place was mixed up.",
    items: [
      { prompt: "Read: 108, 350, 499, 500." },
      { prompt: "Swap: 245 vs 254 — what changed?" },
      { prompt: "Write two numbers with 4 in the tens place." },
    ],
    titleHi: "तीन अंकों की संख्याएँ पढ़ो और बनाओ",
    focusHi: "संख्याएँ ज़ोर से पढ़ो और जगह उलझने पर दोबारा बनाओ।",
    itemsHi: [
      { prompt: "पढ़ो: 108, 350, 499, 500।" },
      { prompt: "बदलो: 245 बनाम 254 — क्या बदला?" },
      { prompt: "ऐसी दो संख्याएँ लिखो जिनमें 4 दहाई की जगह पर हो।" },
    ],
  },
  {
    id: "ws-back-1",
    gapTypeId: "backward-counting",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Backward count ladder",
    focus: "Count back on a ladder from a given start, one step at a time.",
    items: [
      { prompt: "Start at 10. Count back to 1." },
      { prompt: "Start at 20. Count back to 15." },
      { prompt: "Fill: 12, 11, __, 9, __." },
    ],
    titleHi: "उल्टी गिनती की सीढ़ी",
    focusHi: "सीढ़ी पर एक-एक कदम उल्टा गिनो।",
    itemsHi: [
      { prompt: "10 से शुरू करो। 1 तक उल्टा गिनो।" },
      { prompt: "20 से शुरू करो। 15 तक उल्टा गिनो।" },
      { prompt: "भरो: 12, 11, __, 9, __।" },
    ],
  },
  {
    id: "ws-back-2",
    gapTypeId: "backward-counting",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 2,
    title: "Backward jumps across tens",
    focus: "Count backward across a ten, for example 31 → 29.",
    items: [
      { prompt: "Count back: 32, 31, 30, 29, 28." },
      { prompt: "Fill: 21, 20, __, 18." },
      { prompt: "Start at 40. Count back 5 numbers." },
    ],
    titleHi: "दहाई पार करके उल्टी गिनती",
    focusHi: "दहाई पार करके उल्टा गिनो, जैसे 31 → 29।",
    itemsHi: [
      { prompt: "उल्टा गिनो: 32, 31, 30, 29, 28।" },
      { prompt: "भरो: 21, 20, __, 18।" },
      { prompt: "40 से शुरू करो। 5 संख्याएँ उल्टी गिनो।" },
    ],
  },

  /* ── Letter recognition ──────────────────────────────── */
  {
    id: "ws-letterrec-1",
    gapTypeId: "letter-recognition-general",
    subject: "reading",
    grades: [1, 2],
    tier: 1,
    title: "Letter finder",
    focus: "Find, name, and match letters — with picture support.",
    titleHi: "अक्षर खोज",
    focusHi: "अक्षर ढूँढो, नाम बताओ और मिलान करो।",
    items: [
      { kind: "circle", prompt: "Circle every A in this row: A P A B A C A." },
      { kind: "write", prompt: "Write the letter that comes after M: ___ ." },
      { kind: "match", prompt: "Match capital to small: A–a, B–b, D–d, P–p." },
      { kind: "read", prompt: "Name each letter twice: B, D, P, Q." },
    ],
  },
  {
    id: "ws-letterrec-2",
    gapTypeId: "letter-recognition-general",
    subject: "reading",
    grades: [1, 2],
    tier: 2,
    title: "Letter names in words",
    focus: "Spot the first letter of familiar words.",
    titleHi: "शब्दों में अक्षरों के नाम",
    focusHi: "परिचित शब्दों के पहले अक्षर पहचानो।",
    items: [
      { kind: "circle", prompt: "Circle the first letter of each word: ball, doll, kite." },
      { kind: "write", prompt: "Write the missing first letter: _at, _og, _an, _en." },
      { kind: "read", prompt: "Flash the letters b, d, p, q and name them fast." },
      { kind: "fill", prompt: "Fill the missing letter and read the word: c_t, d_g." },
    ],
  },

  /* ── Letter-sound correspondence ─────────────────────── */
  {
    id: "ws-lettersound-1",
    gapTypeId: "letter-sound-correspondence",
    subject: "reading",
    grades: [1, 2],
    tier: 1,
    title: "Sound match",
    focus: "Match each letter to the sound it makes.",
    titleHi: "ध्वनि मिलान",
    focusHi: "हर अक्षर को उसकी ध्वनि से मिलाओ।",
    items: [
      {
        kind: "match",
        prompt: "Match the letter to its sound-word: b–ball, d–dog, s–sun, m–moon.",
      },
      { kind: "circle", prompt: "Circle every b in: b d p q b b d." },
      { kind: "write", prompt: "Write the first sound you hear: _at (b), _og (d), _un (s)." },
      { kind: "read", prompt: "Say the sound of each letter: b, d, m, s, t, p." },
    ],
  },
  {
    id: "ws-lettersound-2",
    gapTypeId: "letter-sound-correspondence",
    subject: "reading",
    grades: [1, 2],
    tier: 2,
    title: "Sounds in short words",
    focus: "Hear the first sound inside real words.",
    titleHi: "छोटे शब्दों में ध्वनियाँ",
    focusHi: "असली शब्दों के भीतर पहली ध्वनि सुनो।",
    items: [
      { kind: "read", prompt: "Read and stretch: b-i-g, d-o-g, s-i-t, m-a-p." },
      { kind: "write", prompt: "Write two words that start with b and two with d." },
      { kind: "circle", prompt: "Which word starts with /b/: dog, bat, mat?" },
      { kind: "fill", prompt: "Fill the first sound: _ox, _og, _at, _un." },
    ],
  },

  /* ── CVC decoding ────────────────────────────────────── */
  {
    id: "ws-cvc-1",
    gapTypeId: "cvc-decoding",
    subject: "reading",
    grades: [1, 2],
    tier: 1,
    title: "Build CVC words",
    focus: "Fill the middle sound and blend the word.",
    titleHi: "CVC शब्द बनाओ",
    focusHi: "बीच की ध्वनि भरकर शब्द बनाओ।",
    items: [
      { kind: "fill", prompt: "Fill the missing middle sound: c_t, d_g, s_n, h_p." },
      { kind: "match", prompt: "Match the word to its picture: cat, dog, sun, pig." },
      { kind: "read", prompt: "Read these words fast: cat, mat, sat, bat." },
      { kind: "write", prompt: "Write three words that rhyme with cat: _at, _at, _at." },
    ],
  },
  {
    id: "ws-cvc-2",
    gapTypeId: "cvc-decoding",
    subject: "reading",
    grades: [1, 2],
    tier: 2,
    title: "CVC in sentences",
    focus: "Read and change CVC words inside short sentences.",
    titleHi: "वाक्यों में CVC शब्द",
    focusHi: "छोटे वाक्यों में CVC शब्द पढ़ो और बदलो।",
    items: [
      { kind: "read", prompt: "Read: The cat and the dog sat on the mat." },
      { kind: "circle", prompt: "Circle the CVC words: The sun is hot. I can hop." },
      {
        kind: "write",
        prompt: "Change the first letter to make a new word: cat → _at, big → _ig, run → _un.",
      },
      { kind: "fill", prompt: "Fill and read: The _og can r_n." },
    ],
  },

  /* ── Word reading accuracy ───────────────────────────── */
  {
    id: "ws-word-1",
    gapTypeId: "word-reading-accuracy",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 1,
    title: "Word flash drill",
    focus: "See the whole word, then read it in a sentence.",
    titleHi: "शब्द फ्लैश अभ्यास",
    focusHi: "पूरा शब्द देखो, फिर वाक्य में पढ़ो।",
    items: [
      { kind: "read", prompt: "Flash and read: the, and, can, look, said, play." },
      { kind: "fill", prompt: "Fill the missing word: The cat ___ on the mat. (sat / sun)" },
      { kind: "write", prompt: "Write the word, cover it, and write it again: the, said, look." },
      { kind: "match", prompt: "Match the word to its meaning: water–drink, play–games, home–house." },
    ],
  },
  {
    id: "ws-word-2",
    gapTypeId: "word-reading-accuracy",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 2,
    title: "Words in action",
    focus: "Choose and use the right everyday word.",
    titleHi: "वाक्यों में शब्द",
    focusHi: "सही शब्द चुनो और इस्तेमाल करो।",
    items: [
      {
        kind: "read",
        prompt: "Read and point to each word: I like to play with my friends.",
      },
      { kind: "circle", prompt: "Circle the word that fits: I ___ to school. (go / goat)" },
      { kind: "write", prompt: "Use each word in a sentence: make, come, little." },
      { kind: "fill", prompt: "Fill the missing word: ___ is the sun warm. (Why / Then)" },
    ],
  },

  /* ── Sentence fluency ────────────────────────────────── */
  {
    id: "ws-sentence-1",
    gapTypeId: "sentence-fluency",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 1,
    title: "Sentence scoops",
    focus: "Read one short phrase in one breath.",
    titleHi: "वाक्य झोली",
    focusHi: "एक साँस में छोटा खंड पढ़ो।",
    items: [
      { kind: "read", prompt: "Read in one breath: The dog can run. / The cat can nap." },
      { kind: "match", prompt: "Match the halves: The sun is / hot. I can / hop." },
      {
        kind: "write",
        prompt: "Rewrite with a capital and a full stop: the cat sat on the mat",
      },
      { kind: "circle", prompt: "Circle the end marks: . ? !" },
    ],
  },
  {
    id: "ws-sentence-2",
    gapTypeId: "sentence-fluency",
    subject: "reading",
    grades: [1, 2, 3],
    tier: 2,
    title: "Sentence builders",
    focus: "Order words, fill gaps, and reread for flow.",
    titleHi: "वाक्य बनाओ",
    focusHi: "शब्दों को क्रम में रखो और वाक्य दोबारा पढ़ो।",
    items: [
      { kind: "fill", prompt: "Fill the missing word: Look at the ___ dog. (big / pig)" },
      { kind: "sequence", prompt: "Put the words in order: mat. on sat The cat" },
      {
        kind: "read",
        prompt: "Read the sentence three times, a little faster each time.",
      },
      { kind: "write", prompt: "Write your own short sentence and read it aloud." },
    ],
  },

  /* ── Oral reading fluency ────────────────────────────── */
  {
    id: "ws-fluency-1",
    gapTypeId: "reading-fluency",
    subject: "reading",
    grades: [2, 3],
    tier: 1,
    title: "Reread for speed",
    focus: "Read a short passage twice, the second time faster.",
    titleHi: "गति के लिए दोबारा पढ़ो",
    focusHi: "छोटा गद्यांश दो बार पढ़ो — दूसरी बार तेज़।",
    items: [
      {
        kind: "read",
        prompt: "Read aloud: Tom and Ana play in the park. The sun is warm. Ana runs to the slide.",
        hint: "Read it twice — first slowly, then a little faster.",
      },
      {
        kind: "circle",
        prompt: "Circle the longer words: together, park, mother, sun.",
      },
      {
        kind: "write",
        prompt: "Write the sentence you found hardest and practise it three times.",
      },
    ],
  },
  {
    id: "ws-fluency-2",
    gapTypeId: "reading-fluency",
    subject: "reading",
    grades: [2, 3],
    tier: 2,
    title: "Phrase scoops",
    focus: "Read in meaning groups instead of word by word.",
    titleHi: "खंडों में पढ़ना",
    focusHi: "शब्द-शब्द की बजाय अर्थ-खंडों में पढ़ो।",
    items: [
      {
        kind: "read",
        prompt: "Read in phrases: The clever crow / found a jug / with a little water.",
      },
      { kind: "sequence", prompt: "Number the sentences in story order: [ ] crow drops stones [ ] water rises [ ] crow drinks." },
      {
        kind: "solve",
        prompt: "Count how many words you read in one minute and write the number: ___.",
      },
    ],
  },

  /* ── Number recognition ──────────────────────────────── */
  {
    id: "ws-number-1",
    gapTypeId: "number-recognition",
    subject: "numeracy",
    grades: [1, 2],
    tier: 1,
    title: "Number name match",
    focus: "Match numerals to their names and find target digits.",
    titleHi: "संख्या-नाम मिलान",
    focusHi: "अंक और नाम का मिलान करो।",
    items: [
      { kind: "match", prompt: "Match: 3–three, 7–seven, 12–twelve, 30–thirty." },
      { kind: "circle", prompt: "Circle every 5: 3 5 8 15 5 25 5 50." },
      { kind: "write", prompt: "Write the number: six ___, ten ___, fourteen ___." },
      { kind: "fill", prompt: "Fill the missing number: 4, 5, __, 7, 8." },
    ],
  },

  /* ── Counting accuracy ───────────────────────────────── */
  {
    id: "ws-count-1",
    gapTypeId: "counting-accuracy",
    subject: "numeracy",
    grades: [1, 2],
    tier: 1,
    title: "Count and write",
    focus: "Fill gaps, order numbers, and count objects.",
    titleHi: "गिनो और लिखो",
    focusHi: "खाली जगह भरो और गिनकर लिखो।",
    items: [
      { kind: "fill", prompt: "Fill: 1, 2, 3, __, 5, __, 7, 8, __, 10." },
      { kind: "write", prompt: "Count the apples (9) and write the number: ___." },
      { kind: "sequence", prompt: "Put in order: 4, 1, 3, 2, 5 → __, __, __, __, __." },
      { kind: "circle", prompt: "Circle the number after 7: 6 8 9." },
    ],
  },
  {
    id: "ws-count-2",
    gapTypeId: "counting-accuracy",
    subject: "numeracy",
    grades: [1, 2],
    tier: 2,
    title: "Count on and back",
    focus: "Count forward from 21 and backward from 30.",
    titleHi: "आगे-पीछे गिनो",
    focusHi: "21 से आगे और 30 से पीछे गिनो।",
    items: [
      { kind: "fill", prompt: "Fill: 21, 22, __, 24, __, 26." },
      { kind: "fill", prompt: "Fill: 30, 29, __, 27, __, 25." },
      { kind: "write", prompt: "Count from 28 to 35 and write the numbers." },
      { kind: "circle", prompt: "Circle the number after 29: 28 30 31." },
    ],
  },

  /* ── Number sequencing ───────────────────────────────── */
  {
    id: "ws-seq-1",
    gapTypeId: "number-sequencing",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Missing numbers",
    focus: "Fill gaps and spot the number that does not fit.",
    titleHi: "लुप्त संख्याएँ",
    focusHi: "छूटी संख्याएँ भरो और गलत संख्या पहचानो।",
    items: [
      { kind: "fill", prompt: "Fill the gaps: 2, 4, 6, __, 10." },
      { kind: "fill", prompt: "Fill the gaps: 11, 12, __, 14, __." },
      { kind: "sequence", prompt: "Write the numbers from 9 to 15 in order." },
      { kind: "circle", prompt: "Circle the number that is out of place: 1, 2, 4, 5, 6." },
    ],
  },
  {
    id: "ws-seq-2",
    gapTypeId: "number-sequencing",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Count on across tens",
    focus: "Keep the sequence steady across a decade jump.",
    titleHi: "दहाई पार करके गिनो",
    focusHi: "दहाई की छलाँग पर भी क्रम बनाए रखो।",
    items: [
      { kind: "fill", prompt: "Fill: 27, 28, 29, __, 31." },
      { kind: "fill", prompt: "Fill: 38, 39, __, 41, 42." },
      { kind: "write", prompt: "Count forward from 55 to 65 and write the numbers." },
      { kind: "circle", prompt: "Circle every number where the tens digit changes: 27 28 29 30 31." },
    ],
  },

  /* ── Before / after ──────────────────────────────────── */
  {
    id: "ws-beforeafter-1",
    gapTypeId: "before-after",
    subject: "numeracy",
    grades: [1, 2],
    tier: 1,
    title: "Before and after ladder",
    focus: "Name the neighbours of a number.",
    titleHi: "पहले-बाद की सीढ़ी",
    focusHi: "हर संख्या के पड़ोसी बताओ।",
    items: [
      { kind: "fill", prompt: "Write the number before 8: ___ ." },
      { kind: "fill", prompt: "Write the number after 8: ___ ." },
      { kind: "fill", prompt: "Fill: __, 15, __ · __, 30, __." },
      { kind: "circle", prompt: "Circle the number that comes before 20: 19 21." },
    ],
  },
  {
    id: "ws-beforeafter-2",
    gapTypeId: "before-after",
    subject: "numeracy",
    grades: [1, 2],
    tier: 2,
    title: "Neighbours across tens",
    focus: "Before and after across 10, 20, and 30.",
    titleHi: "दहाई पर पड़ोसी",
    focusHi: "10, 20 और 30 के आस-पास पहले-बाद बताओ।",
    items: [
      { kind: "fill", prompt: "Fill: __, 10, __ · __, 20, __." },
      { kind: "fill", prompt: "Fill: __, 30, __ · __, 40, __." },
      { kind: "write", prompt: "Write the number before and after 29: __, 29, __." },
      { kind: "circle", prompt: "Circle the number that comes after 39: 40 38." },
    ],
  },

  /* ── Number comparison ───────────────────────────────── */
  {
    id: "ws-compare-1",
    gapTypeId: "number-comparison",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Bigger or smaller",
    focus: "Circle the bigger or smaller number and use > and <.",
    titleHi: "बड़ा या छोटा",
    focusHi: "बड़ी-छोटी संख्या पर गोला लगाओ और > < लिखो।",
    items: [
      { kind: "circle", prompt: "Circle the bigger number: 7 or 9 · 15 or 12." },
      { kind: "circle", prompt: "Circle the smaller number: 20 or 19 · 34 or 43." },
      { kind: "write", prompt: "Write > or < : 8 __ 5 · 12 __ 21." },
      { kind: "fill", prompt: "Write any number bigger than 30: ___ ." },
    ],
  },
  {
    id: "ws-compare-2",
    gapTypeId: "number-comparison",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Compare three-digit numbers",
    focus: "Compare by hundreds, then tens, then ones.",
    titleHi: "तीन अंकों की तुलना",
    focusHi: "सैकड़ा, फिर दहाई, फिर इकाई देखकर तुलना करो।",
    items: [
      { kind: "circle", prompt: "Circle the bigger number: 108 or 180." },
      { kind: "circle", prompt: "Circle the smaller number: 245 or 254." },
      { kind: "write", prompt: "Write > or < : 399 __ 401 · 500 __ 499." },
      { kind: "fill", prompt: "Write any number between 300 and 400: ___ ." },
    ],
  },

  /* ── Tens and ones ───────────────────────────────────── */
  {
    id: "ws-tensones-1",
    gapTypeId: "tens-ones",
    subject: "numeracy",
    grades: [1, 2],
    tier: 1,
    title: "Tens and ones draw",
    focus: "Show numbers with sticks and fill the place table.",
    titleHi: "दहाई-इकाई बनाओ",
    focusHi: "छड़ियों से संख्या दिखाओ और तालिका भरो।",
    items: [
      { kind: "solve", prompt: "Show 13 with sticks: 1 ten and 3 ones." },
      { kind: "fill", prompt: "Fill: 25 = __ tens and __ ones." },
      { kind: "write", prompt: "Write the number: 3 tens and 4 ones = ___ ." },
      { kind: "circle", prompt: "Circle the number with 2 tens: 42 12 29." },
    ],
  },
  {
    id: "ws-tensones-2",
    gapTypeId: "tens-ones",
    subject: "numeracy",
    grades: [1, 2],
    tier: 2,
    title: "Tens and ones swap",
    focus: "Notice what changes when tens and ones swap places.",
    titleHi: "दहाई-इकाई बदलो",
    focusHi: "दहाई और इकाई बदलने पर क्या बदलता है देखो।",
    items: [
      { kind: "solve", prompt: "Build 47 with sticks: __ tens and __ ones." },
      { kind: "fill", prompt: "Fill: 60 = __ tens and __ ones." },
      { kind: "write", prompt: "Write the number: 7 tens and 2 ones = ___ ." },
      { kind: "circle", prompt: "Circle the number with 0 ones: 40 34 19." },
    ],
  },

  /* ── Addition facts ──────────────────────────────────── */
  {
    id: "ws-add-1",
    gapTypeId: "addition-facts",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Addition facts",
    focus: "Solve small sums and match sums to answers.",
    titleHi: "जोड़ के सवाल",
    focusHi: "छोटे जोड़ हल करो और उत्तर मिलाओ।",
    items: [
      { kind: "solve", prompt: "Solve: 2 + 3 = __ · 4 + 4 = __." },
      { kind: "solve", prompt: "Solve: 5 + 6 = __ · 7 + 8 = __." },
      { kind: "fill", prompt: "Fill the missing addend: 3 + __ = 10." },
      { kind: "match", prompt: "Match the sum: 2+2–4, 3+5–8, 6+4–10." },
    ],
  },
  {
    id: "ws-add-2",
    gapTypeId: "addition-facts",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Add larger numbers",
    focus: "Add two-digit numbers with care for place value.",
    titleHi: "बड़ी संख्याएँ जोड़ो",
    focusHi: "स्थानीय मान का ध्यान रखते हुए बड़े जोड़ हल करो।",
    items: [
      { kind: "solve", prompt: "Solve: 13 + 5 = __ · 24 + 10 = __." },
      { kind: "solve", prompt: "Solve: 35 + 27 = __ · 48 + 19 = __." },
      { kind: "write", prompt: "Write your own addition story and solve it." },
      { kind: "fill", prompt: "Fill: 20 + __ = 50." },
    ],
  },

  /* ── Subtraction facts ───────────────────────────────── */
  {
    id: "ws-sub-1",
    gapTypeId: "subtraction-facts",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Subtraction facts",
    focus: "Solve take-away facts and match to answers.",
    titleHi: "घटाव के सवाल",
    focusHi: "घटाव हल करो और उत्तर मिलाओ।",
    items: [
      { kind: "solve", prompt: "Solve: 5 − 2 = __ · 9 − 4 = __." },
      { kind: "solve", prompt: "Solve: 10 − 6 = __ · 12 − 7 = __." },
      { kind: "fill", prompt: "Fill: 8 − __ = 5." },
      { kind: "match", prompt: "Match: 7−3–4, 9−2–7, 10−4–6." },
    ],
  },
  {
    id: "ws-sub-2",
    gapTypeId: "subtraction-facts",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Subtract larger numbers",
    focus: "Subtract two-digit numbers with careful regrouping.",
    titleHi: "बड़ी संख्याएँ घटाओ",
    focusHi: "बड़े घटाव सावधानी से हल करो।",
    items: [
      { kind: "solve", prompt: "Solve: 20 − 8 = __ · 34 − 12 = __." },
      { kind: "solve", prompt: "Solve: 50 − 27 = __ · 63 − 38 = __." },
      { kind: "write", prompt: "Write a take-away story and solve it." },
      { kind: "fill", prompt: "Fill: 40 − __ = 25." },
    ],
  },

  /* ── Number bonds ────────────────────────────────────── */
  {
    id: "ws-bonds-1",
    gapTypeId: "number-bonds",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Bonds to 10",
    focus: "Fill the partner that makes 10 and match pairs.",
    titleHi: "10 के जोड़े",
    focusHi: "10 बनाने वाला साथी भरो और जोड़े मिलाओ।",
    items: [
      { kind: "fill", prompt: "Fill the partner: 1 + __ = 10 · 3 + __ = 10." },
      { kind: "fill", prompt: "Fill the partner: 6 + __ = 10 · 8 + __ = 10." },
      { kind: "match", prompt: "Match the pairs that make 10: 2–8, 4–6, 7–3." },
      { kind: "write", prompt: "Write all the ways to make 10 using two numbers." },
    ],
  },
  {
    id: "ws-bonds-2",
    gapTypeId: "number-bonds",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Bonds to 20, 30, 50",
    focus: "Fill missing partners for larger target numbers.",
    titleHi: "20, 30, 50 के जोड़े",
    focusHi: "बड़ी लक्ष्य संख्याओं के लिए साथी भरो।",
    items: [
      { kind: "fill", prompt: "Fill: 13 + __ = 20 · 7 + __ = 20." },
      { kind: "fill", prompt: "Fill: __ + 15 = 30 · 25 + __ = 50." },
      { kind: "write", prompt: "Write two pairs that make 30." },
      { kind: "circle", prompt: "Circle the partner of 18 that makes 20: 2 3 1." },
    ],
  },

  /* ── Skip counting ───────────────────────────────────── */
  {
    id: "ws-skip-1",
    gapTypeId: "skip-counting",
    subject: "numeracy",
    grades: [1, 2, 3],
    tier: 1,
    title: "Skip-count paths",
    focus: "Fill the steps when counting by 2s, 5s, and 10s.",
    titleHi: "छलाँग गिनती के रास्ते",
    focusHi: "2, 5 और 10 की छलाँग के कदम भरो।",
    items: [
      { kind: "fill", prompt: "Count by 2s: 2, 4, __, 8, __." },
      { kind: "fill", prompt: "Count by 5s: 5, 10, __, 20, __." },
      { kind: "fill", prompt: "Count by 10s: 10, 20, __, 40, __." },
      {
        kind: "circle",
        prompt: "Circle every number you say when counting by 5s: 3 5 8 10 15 22 25.",
      },
    ],
  },
  {
    id: "ws-skip-2",
    gapTypeId: "skip-counting",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Skip-count longer paths",
    focus: "Keep the rhythm across bigger numbers.",
    titleHi: "लंबी छलाँग गिनती",
    focusHi: "बड़ी संख्याओं पर भी लय बनाए रखो।",
    items: [
      { kind: "fill", prompt: "Count by 10s: 45, 55, __, 75, __." },
      { kind: "fill", prompt: "Count by 5s: 60, 65, __, 75, __." },
      { kind: "write", prompt: "Count by 2s from 20 to 30 and write the numbers." },
      { kind: "circle", prompt: "Circle the numbers you say when counting by 10s from 30: 30 35 40 45 50." },
    ],
  },

  /* ── Word problems ───────────────────────────────────── */
  {
    id: "ws-wordprob-1",
    gapTypeId: "word-problems",
    subject: "numeracy",
    grades: [2, 3],
    tier: 1,
    title: "Story problems",
    focus: "Turn a one-step story into a number sentence.",
    titleHi: "कहानी वाले सवाल",
    focusHi: "एक-चरणीय कहानी को संख्या वाक्य में बदलो।",
    items: [
      {
        kind: "solve",
        prompt: "Rita has 3 apples. She gets 2 more. How many now?",
      },
      {
        kind: "solve",
        prompt: "8 children are on a bus. 3 get off. How many are left?",
      },
      {
        kind: "write",
        prompt: "Draw the story for question 1, then write the number sentence.",
      },
      {
        kind: "match",
        prompt: "Match each story to its sum: adding–3 + 2, taking away–8 − 3.",
      },
    ],
  },
  {
    id: "ws-wordprob-2",
    gapTypeId: "word-problems",
    subject: "numeracy",
    grades: [2, 3],
    tier: 2,
    title: "Harder story problems",
    focus: "Solve two-step stories with bigger numbers.",
    titleHi: "कठिन कहानी वाले सवाल",
    focusHi: "बड़ी संख्याओं वाली दो-चरणीय कहानियाँ हल करो।",
    items: [
      {
        kind: "solve",
        prompt: "There are 12 pens in a box. 5 are blue and the rest are red. How many are red?",
      },
      {
        kind: "solve",
        prompt: "A shop has 20 toffees. 8 are sold. How many are left?",
      },
      {
        kind: "write",
        prompt: "Write your own story problem for 14 − 6 and solve it.",
      },
    ],
  },
];

export function selectWorksheetTemplate(
  gapTypeId: string,
  grade: Grade,
  subject: Subject,
  tier: WorksheetTier,
): WorksheetTemplate | undefined {
  const pool = WORKSHEET_TEMPLATES.filter(
    (t) => t.gapTypeId === gapTypeId && t.subject === subject && t.grades.includes(grade),
  );
  if (!pool.length) return undefined;
  return (
    pool.find((t) => t.tier === tier) ??
    pool.sort((a, b) => a.tier - b.tier)[pool.length - 1] ??
    pool[0]
  );
}

export function nextTier(current: WorksheetTier): WorksheetTier {
  return current >= 3 ? 3 : ((current + 1) as WorksheetTier);
}
