import { formatShortDate } from "@/domain/ids";
import type { Student, WorksheetInstance } from "@/domain/types";
import { getGapType } from "@/domain/competency-registry";

export default function WorksheetPreview({
  sheet,
  student,
  gapTypeId,
}: {
  sheet: WorksheetInstance;
  student: Student;
  gapTypeId?: string;
}) {
  const gap = gapTypeId ? getGapType(gapTypeId) : undefined;
  return (
    <article className="rounded-3xl border border-border bg-card p-6 shadow-soft print:rounded-none print:border-0 print:shadow-none">
      <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Practice sheet · Tier {sheet.tier}
      </p>
      <h1 className="mt-1 font-heading text-2xl font-bold text-foreground">{sheet.title}</h1>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{sheet.focus}</p>
      <div className="mt-4 grid grid-cols-2 gap-2 text-sm">
        <p>
          <span className="text-muted-foreground">Student</span>
          <br />
          <span className="font-semibold">{student.name}</span>
        </p>
        <p>
          <span className="text-muted-foreground">Grade / Roll</span>
          <br />
          <span className="font-semibold">
            Grade {student.grade} · {student.rollNo}
          </span>
        </p>
        <p>
          <span className="text-muted-foreground">Date</span>
          <br />
          <span className="font-semibold">{formatShortDate(sheet.assignedAt)}</span>
        </p>
        <p>
          <span className="text-muted-foreground">Focus gap</span>
          <br />
          <span className="font-semibold">{gap?.label ?? "Linked skill gap"}</span>
        </p>
      </div>
      <ol className="mt-6 space-y-3">
        {sheet.items.map((item, i) => (
          <li key={i} className="rounded-2xl bg-accent/80 px-4 py-3 text-[15px] leading-relaxed">
            <span className="mr-2 font-heading font-bold text-primary">{i + 1}.</span>
            {item.prompt}
            {item.hint ? (
              <span className="mt-1 block text-sm text-muted-foreground">{item.hint}</span>
            ) : null}
          </li>
        ))}
      </ol>
      <p className="mt-6 text-xs leading-relaxed text-muted-foreground">
        From the tagged worksheet bank — not generated by a language model. Adjust only the
        matching drill if the gap remains after reassessment.
      </p>
    </article>
  );
}
